#+BEGIN_EXPORT html
---
layout: post
title: Anton S. Kosinov
tagline: " Keep clear"
permalink: /cv.html
categories: [info, about me]
tags: [CV, Emacs, Python, Literate Programming]
---
#+END_EXPORT

#+STARTUP: showall
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2


* Dense and terse overview
  #+BEGIN_SRC python
    class Person(object):

        def __init__(self):
            self.name = "Anton Kosinov"
            self.birth_date = "1978-02-23"
            self.father = "nuclear phisicist"
            self.mother = "chemical engineer"
            self.ant = "physics teacher"
            self.grandmother = "Russian literature teacher"

        def schooling(self):
            self.succeed = ["Republican Physics Olympiad winner",]

    class Engineer(Person):
        """The technical tasks solver"""

        def naval_college(self):
            self.education = {  # not only a self-education, of cause
                "area of study" : "nuclear power plants",
                "specialize on" : "technological processes automation"}
            self.succeed += ["English language Olympiad winner",
                             "Bachelor degree in automation"]

        def nuclear_power_plant(self):
            self.first_job = {
                "" : ""}

        def review_challenge(self, issue):
            """Take a close look on the challenge"""
            return corollary

        def divide_and_conquer(self, corollary):
            """Split entire challenge into a list of 
            relatively simple tasks"""
            return challenge_decomposed

        def resolve_challenge(self, challenge_decomposed):
            """ """
            return solution

    class SoftwareEngineer(Engineer):
        """
        Software-specific problem-solver
        Inherits all general-purpose engineer's
        functions and has the specific ones:
        """

        def guess_algorithm(self, issue):
            return pertinent_algorithm

        def complexity_control(self, software):
            pass

  #+END_SRC
* Preamble

** Who am I
   First of all I'm happy father and husband. The second one is my
   innate hyper-curiousity. In most cases I've succeeded on this by my
   solid patience and immutable humor sense. 

   And the third and last about me:

   #+BEGIN_QUOTE
   There are rules in our Universe and all stuff around us strictly
   follows these rules. The Gravity, Electricity and Nuclear Reactions
   are kings and queens in their realm and our world simultaneously.   
   #+END_QUOTE
   
   *Happy grows in the mind*

** What I do

   I'm a data-driven person. Unconsciously I'm trying to know much
   details about my personal environment. It's just my innate
   hyper-curiosity. It forces me, it inspires me, it is my passion,
   hobby and my live-style.

   Thus: *data, data, data*

** What I fun for

   In the secondary school I've noticed that machines are much
   stronger than people. The short introduction about how difficult is
   to enslave the iron helpers I got when I learned car-driving
   method. It was awesome.

   But there are long time gone, and now I focused on /programming/
   machines to do large amount of job on incredible speed. It's
   partially a science, but on another side it might be a sport in the
   same time.

   Hence: *machines, speed, programming*

* Tuition

** Secondary School

** Naval College

** University

* Skills

** Ubuntu

** Python

** JavaScript

** Emacs

** HTML5

** Algorithms

* Techics

** Fluent English

** Model Thinking

** Test-Driven Development


* Experience

** Web Crawling

** Data Processing

** Mental Athletics

** Data Visualization

* Payments

* Feedback
  Feel free to leave any comments below. It all are acceptable by
  default.
  
* Anton Kosinov

Role: Senior Python developer

Applied technology: Mental Athletics

Key achievements: I started to program in 1992 for scientific digital
calculator MK-61. It was 104 directives sequence but it's in charge to
calculate 100! in a couple hours. And even the Moon landing simulator
was there; Soon I assembled a graphical cluster of memory ZX Spectrum;
i486 was extraordinary fast and I met initially Borland’s dBase; In
1995 fall I started to studying Data Science and Automation Technology
in the naval college classes; In 2000 I found there are no support for
OS Windows in my country; In 2005 I bought Athlon i686 and installed
Red Hat Linux on it. It caused a seismic shift in my mind. Open Source
works(!); By sequential studying bash, HTML, CSS, Emacs, Python2,
MySQL and BigTable in 2008 I deployed my first web application on
Google App Engine. And jQuery was there also; In 2009 I started to
work as a freelancer at oDesk with Scrapy 0.10 In 2012 I dissected
PostgreSQL, Amazon Web Services and started to utilize their power and
flexibility; 2013 NoSQL was discovered. It’s just an unstructured
storage ;-) 2014 I’ve upgrade my skill-set by Coursera’s MOOCs:
Learning to Learn Model Thinking 2015 Quora reading and deep thinking
about everything. 2016 : Python3 treatment and migration Git with
Magit functional access essential training OOP design principles
scrutiny TDD concepts and approaches study Literate programming with
Emacs Babel Blogging with Jekyll Quora reading as natural English
source Computer algorithms studying Coding skills honing with CodeWars
Tutoring and conveying these skills to my wife

Employment:

2009 – 2016 freelance full stack Python web application developer

Personal skills:

capable to learn joyfully and fast persistence and patience

Personal: reading-addicted
