#+BEGIN_EXPORT html
---
layout: post
title: Debian 9 post-installation
tagline: " arrangement automation"
permalink: /debian/post-installation.html
categories: [Debian, DevEnv]
tags: [post-installation, arrangement, automation]
---
#+END_EXPORT

#+STARTUP: showall
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export

* Goal definition

  When you're dived in depth of software development with =Debian= as
  a main operational system sometimes it might emerge the urge to
  install it on a new host. As the current environment is homely and
  handy to use thus the aim is ~just to replicate~ it.

* Software installation

  #+BEGIN_SRC sh
    apt-get install -y htop emacs25 gkrellm openssh-server virtualenv \
    sqlite3 mariadb-client mariadb-server
  #+END_SRC

* FileTree extension

  On my point of view the most convenient place to put some shared
  data on your ~Debian 9~ host is =/usr/local/share/=

** Check the existing folders
   #+BEGIN_SRC sh
   ls -la /usr/local/share/
   #+END_SRC

   #+RESULTS:
   #+begin_example
   total 52
   drwxrwsr-x 13 root   staff  4096 Jul 21 12:04 .
   drwxrwsr-x 10 root   staff  4096 Jul 10 15:22 ..
   drwxr-sr-x  3 root   staff  4096 Jul 21 12:04 anki
   drwxr-sr-x  2 root   staff  4096 Aug  2 06:31 applications
   drwxrwsr-x  2 root   staff  4096 Jun 20 04:18 ca-certificates
   drwxrwsr-x  4 root   staff  4096 Jul 10 17:23 emacs
   drwxrwsr-x  2 root   staff  4096 Jun 20 04:18 fonts
   drwxrwsr-x  3 root   staff  4096 Jul 21 12:04 man
   drwxr-sr-x  2 root   staff  4096 Jul 21 12:04 pixmaps
   drwxrwsr-x  7 root   staff  4096 Jul 10 15:22 sgml
   drwxrwsr-x  6 root   staff  4096 Jul 10 15:22 xml
 #+end_example

** Check-up user groups

   By default convention the user don't have wright access onto
   =/usr/local/=, [[https://wiki.debian.org/SystemGroups][but]] staff group is a special case:
   #+BEGIN_QUOTE
   staff: Allows users to add local modifications to the system
   (/usr/local) without needing root privileges...
   #+END_QUOTE

   Initially there are no users in it:

   #+BEGIN_SRC sh
   groups | grep staff
   echo "---"
   groups alioth | grep staff
   #+END_SRC

   #+RESULTS:
   : ---

*** Add user to group ~staff~

    #+BEGIN_EXAMPLE
    # usermod -aG staff alioth
    #+END_EXAMPLE

    *or* equivalent:

    #+BEGIN_EXAMPLE
    # adduser alioth staff
    #+END_EXAMPLE

*** *Re-login*

    To up-to-date group permissions.

*** And check groups now:
   
    #+BEGIN_SRC sh
    groups | grep staff
    echo "==="
    groups alioth | grep staff
    #+END_SRC

    #+RESULTS:
    : alioth cdrom floppy sudo audio dip video plugdev staff netdev bluetooth scanner
    : ===
    : alioth : alioth cdrom floppy sudo audio dip video plugdev staff netdev bluetooth scanner

*** Testing

    Is it possible to touch file in ~/usr/local/share/~ right now?
   
    #+BEGIN_SRC sh
    cd /usr/local/share/
    touch test.file.txt
    ls -la | grep test
    rm test.file.txt
    echo "++++"
    ls -la | grep test
    #+END_SRC

    #+RESULTS:
    : -rw-r--r--  1 alioth staff     0 Aug  2 18:39 test.file.txt
    : ++++


* Software development environment configuring

* Testing
