#+BEGIN_EXPORT html
---
layout: post
title: Porteus
tagline: " be free anywhere"
permalink: /porteus/load-to-ram-config.html
categories: [Porteus, DevEnv]
tags: [live USB, load to RAM, configuration]
---
#+END_EXPORT

#+STARTUP: showall
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export

* Intro

** Distinct features
   
   As you might expect there are few considerable incentives to use
   ~Porteus~ as your ~DevEnv~:

   - It is portable;
   - It might be launched on any host;
   - It is a lightweight version of ~Linux~;
   - It might be loaded directly into RAM (!)


   Of course it is not a /silver bullet/, but sometimes it is useful to
   utilize its peculiar advantages.

   This article might shed a light on a much /attractive/ ~Porteus'~
   feature: its capability to load into RAM of your PC when all data
   on your HDD stay detached. It might be defined as completely
   _non-intrusive installation_ of *UNIX* OS.

** Comparison with other live-USB distributions

   There is an abundance of similar by main features live-USB Linux
   distributions, but the *Load to RAM* is a killer one:

   - OS allocates in RAM, thus:
     - it allows to do all what you want to do on incredible speed;
     - it prevents USB-stick damage by writing incremental changes;
     - it grants you permission to modify it manually.

   As an opposite experience I have had ~Ubuntu~ USB-stick which was
   similar by functionality and it was completely ruined after ~70
   PC's boot-ing. Seems like /incremental changes writing/ demolished
   it. And in addition it is unavoidable there.

** Conclusion
   
   Suppose it is enough to ensure you to make your own ~Porteus~
   live-USB and take a challenge of total portability.

* Steps

** Set all stuff on the places

** Open =root= terminal session

** Mount partition with ~Porteus~

** Generate:

   ~Porteus~ saves incremental changes in =.xzm= format.

   #+BEGIN_EXAMPLE
   # save-changes /mnt/sdc1/porteus/optional/extension_001.xzm
   #+END_EXAMPLE

   Where =/mnt/sdc1/porteus/optional/= is a path to your ~Porteus~
   Live-USB, and =extension_001.xzm= is a filename itself.

** Edit config:

   #+BEGIN_EXAMPLE
   # nano /mnt/sdc1/boot/syslinux/porteus.cfg
   #+END_EXAMPLE

* Test

  Try to configure <CapsLock> as an additional <Ctrl>:
  
  #+BEGIN_SRC sh
  /usr/bin/setxkbmap -option "ctrl:nocaps"
  /usr/bin/setxkbmap -option "caps:ctrl_modifier"
  #+END_SRC
