#+BEGIN_EXPORT html
---
layout: page
title: Google Calendar
tagline: 'meets with org-agenda'
permalink: /emacs/org-agenda/google-calendar.html
categories: [Emacs, Learning Technology, Time Management]
tags: [org, agenda, icalendar]
---
#+END_EXPORT

#+STARTUP: showall
#+OPTIONS: tags:nil toc:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
* Introduction

  Without any doubt ~time management~ is a cornerstone of
  productivity. Hence lets take a closer look at [[https://en.wikipedia.org/wiki/Time_management][this technique]]:

  #+BEGIN_QUOTE
  Time management is the process of planning and exercising conscious
  control of time spent on specific activities, especially to increase
  effectiveness, efficiency or productivity. It is a juggling act of
  various demands of study, social life, employment, family, and
  personal interests and commitments with the finiteness of time.
  #+END_QUOTE

  The scope of this article is ~time management~ in =Emacs=, thus take
  a look on existent toolbox inside it.

  The aim of this article is to show how-to compose your personal
  agenda in =Emacs'= =Org-mode= and share it with Google Calendar.

* Overview

** Emacs' side

   As expected =Emacs= has a set of prepared tools to manage your time.

*** Diary

    Is an innate =Emacs'= feature:

    #+BEGIN_QUOTE
    The Emacs diary keeps track of appointments or other events on a
    daily basis, in conjunction with the calendar. To use the diary
    feature, you must first create a diary file containing a list of
    events and their dates. Then Emacs can automatically pick out and
    display the events for today, for the immediate future, or for any
    specified date.
    #+END_QUOTE

*** Agenda

    Is =Org= feature and it might be combined with the =Diary=

    Seems like it is the most suitable form to compose your personal
    time-schedule. Just write some significant points into the file in
    accordion with special rules and using some peculiar attributes.

    [[https://www.gnu.org/software/emacs/manual/html_node/org/Agenda-Views.html][Full specification]]

** Google Calendar

   Is an extremely powerful, flexible and convenient tool to have in
   the hands.

   #+BEGIN_QUOTE
   Google Calendar allows users to create and edit events. Reminders
   can be enabled for events, with options available for type and
   time. Event locations can also be added, and other users can be
   invited to events.

   ...

   Users can invite other people to events; for other Google Calendar
   users, the event becomes visible in their calendar, and for
   non-Google Calendar users, an email will have options for "Yes",
   "No", or "Maybe". Privacy settings allow the user to define the
   levels of public visibility of the entire calendar or individual
   events. Although the calendar defaults to showing users event times
   in their local time, users can specify a different time zone for an
   event. Users can enable or disable the visibility of special
   calendars, including a Birthdays calendar, that automatically
   retrieves dates of births from a user's Google contacts and
   displays the dates on a yearly basis, and a Holidays calendar, a
   country-specific calendar featuring dates of special occasions.
   #+END_QUOTE

   E.g. =Google Calendar= capable to share a personal agenda among
   team members.


* Composing agenda file(s)

  Nothing especial and habitually precise defined in the official
  documentation.

* Exporting agenda file(s)

  Just try to evaluate export through interactive export menu bu
  typing: =C-c C-e c f= and get a pristine =.ics= file.

  #+BEGIN_SRC sh :results output
  cat ../lib/org/agenda/main.ics
  #+END_SRC

  #+RESULTS:
  : BEGIN:VCALENDAR
  : VERSION:2.0
  : X-WR-CALNAME:main
  : PRODID:-//Anton S. Kosinov//Emacs with Org mode//EN
  : X-WR-TIMEZONE:EET
  : X-WR-CALDESC:Mental Athlete ToDo List
  : CALSCALE:GREGORIAN
  : END:VCALENDAR

  It is absolutely normal - an empty template with no events at all.
  With purpose to catch all unfinished events and cramp it in our
  =.ics= file you need to modify =org-icalendar-include-todo=
  variable.

  It is not a rocket science:
  =C-h v org-icalendar-include-todo=

  Following =Emacs= customization procedure I choose ~t include tasks
  that are not in DONE state.~

  Now it is time to test our customisation settings: =C-c C-e c f= and
  review the content of =.ics= file:

  #+BEGIN_SRC sh :results output
  cat ../lib/org/agenda/main.ics
  #+END_SRC

  #+RESULTS:
  #+begin_example
  BEGIN:VCALENDAR
  VERSION:2.0
  X-WR-CALNAME:main
  PRODID:-//Anton S. Kosinov//Emacs with Org mode//EN
  X-WR-TIMEZONE:EET
  X-WR-CALDESC:Mental Athlete ToDo List
  CALSCALE:GREGORIAN
  BEGIN:VTODO
  UID:TODO-2a126636-8cbc-4065-a723-67b4782e0c3a
  DTSTAMP:20180220T160118Z
  DTSTART:20180220T180100
  DUE:20180215T130000
  SUMMARY:Past tenses
  DESCRIPTION:Elaborate an initial [org-drill]\n(file:/usr/local/git/0--key/l
   ib/org/eng_grammar.org::*Past%20simple)
  CATEGORIES:main
  SEQUENCE:1
  PRIORITY:5
  STATUS:NEEDS-ACTION
  END:VTODO
  BEGIN:VTODO
  UID:TODO-9f4809fc-2266-4b84-bfae-3b885405a6aa
  DTSTAMP:20180220T160118Z
  DTSTART:20180209T082000
  SUMMARY:Calendar
  CATEGORIES:main
  SEQUENCE:1
  PRIORITY:5
  STATUS:COMPLETED
  END:VTODO
  BEGIN:VTODO
  UID:TODO-c7600f16-4bc0-4d1d-8eec-c68ab54cf4d4
  DTSTAMP:20180220T160118Z
  DTSTART:20180216T160000
  SUMMARY:Agenda rigorous dissection
  DESCRIPTION:• Export int .ics\n• Import into specific Google Calendar
  CATEGORIES:main
  SEQUENCE:1
  PRIORITY:5
  STATUS:NEEDS-ACTION
  END:VTODO
  BEGIN:VTODO
  UID:TODO-5497d2b0-3e83-45d3-b5f1-4f62c2d5cf82
  DTSTAMP:20180220T160118Z
  DTSTART:20180216T170000
  SUMMARY:Capture
  DESCRIPTION:Make capture for org-drill items generation with minimal interr
   uption
  CATEGORIES:main
  SEQUENCE:1
  PRIORITY:5
  STATUS:NEEDS-ACTION
  END:VTODO
  BEGIN:VTODO
  UID:TODO-33c7d5ac-d8a1-474f-b4ce-a2a09fb95c04
  DTSTAMP:20180220T160118Z
  DTSTART:20180217T123000
  SUMMARY:Macros
  DESCRIPTION:To convert `voca-builder' item into `Drill'
  CATEGORIES:main
  SEQUENCE:1
  PRIORITY:5
  STATUS:NEEDS-ACTION
  END:VTODO
  BEGIN:VTODO
  UID:TODO-9af7d91f-b31c-435b-8411-91d144d7a50b
  DTSTAMP:20180220T160118Z
  DTSTART:20180213T083000
  SUMMARY:Introduction
  CATEGORIES:main
  SEQUENCE:1
  PRIORITY:5
  STATUS:NEEDS-ACTION
  END:VTODO
  BEGIN:VTODO
  UID:TODO-d0502a28-505b-4639-b7db-d7b264dc1019
  DTSTAMP:20180220T160118Z
  DTSTART:20180217T133000
  SUMMARY:Extract the binary terminology
  CATEGORIES:main
  SEQUENCE:1
  PRIORITY:5
  STATUS:NEEDS-ACTION
  END:VTODO
  END:VCALENDAR
  #+end_example


* Preparing a peculiar Google Calendar

* Importing .ics file
