#+BEGIN_EXPORT html
---
layout: post
title: Bookmarking everything
tagline: " by means of Emacs' toolbox"
permalink: /emacs/bookmark-plus.html
categories: [literate programming, emacs]
tags: [Bookmark+, manual+]
---
#+END_EXPORT

#+STARTUP: showall
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
* Preface

  #+BEGIN_QUOTE
  In preposition that the reader is an eager life-long learner and
  overcame the stage of unconscious and spontaneous learning. Thus it
  becomes obvious that the best approach to learn something huge is to
  split the whole task into the plenty of tiny tidbits of knowledge,
  determine the sequential and independent ones and take an attempt to
  study them all in a =mingled form=.
  #+END_QUOTE

  =Bookmark+= is such sophisticated Emacs' extension thus it might be
  unavoidable to use it on the daily basic ASAP. Of course as all
  useful packages it is a bit knotty documented which implicate
  difficulties in its taming. This article is a demure attempt to
  dismantle a hidden power of =Bookmark+= by rigorous dissection all
  its features, functions and even quirks and puns.

* Distinct features

  #+BEGIN_QUOTE
  Richer bookmarks. They record more. They are more accurate.
  #+END_QUOTE
** An optional annotation
*** Any file, URL or bookmark as annotation
** Sophisticated tagging
*** Any tag might be even an attribute
** Multitude bookmarks with the same name
   but distinct by their content
** Meta-data about bookmark
*** Counting number of visits
** A sequence of bookmarks as a chain
   it is possible to tie together several bookmarks
** The region of text as bookmark
** An adaptive relocation
   much precise when text nearby your bookmark was changed


* Additional features

** Autofile

** Dired

** Dired-tree

** Bookmark-list

** Bookmark-file

** Desktop

** Gnus

** Non-file (buffer)

** Function

** Sequence (composite)

** Keyboard-macro set

** Set of ~Lisp~ variables

** Snippet

* Installation

** Situation in the past

   Seems it is an absolutely trivial procedure even for inexperienced
   ~Emacs~ user in particular :-) All what you need to do is to do it
   by your package manager.

   1. Open ~Emacs~ package manager: =M-x packages-list-packages=;
   2. Find ~Bookmark+~ there: =C-s kmark=;
   3. Choose it for installation by typing =i=;
   4. Execute your choice by typing =x=;
   5. Have a ~fun~


** Current state of things

   Nowadays the current state of things shifted significantly and
   you'll restricted to install ~Bookmark+~ from its sources, because
   for unknown reason this package was expelled out from ~Emacs~
   official repositories. Habitually there are several steps to
   accomplish:

   1. Download all necessary files;
   2. Put it together somewhere you're allocated ~Emacs~ lisp;
   3. Add this folder to ~load-path~:
      #+BEGIN_SRC elisp
      (add-to-list 'load-path "/usr/local/share/emacs/site-lisp/bookmark-plus/")
      #+END_SRC
   4. Allow to ~Emacs~ launch this pacage at start by putting:
      #+BEGIN_SRC elisp
      requre 'bookmark+
      #+END_SRC

* Test launch

  I'm absolutely sure that you already have several bookmarks, hence
  it would be curious to look at them in a bit different point fo view.
  ~Bookmark+~ pervectly compatible with vanilla version of
  ~bookmarks~, thus all that require to do is just type =C-x p e= and
  take a peep at the same object at completlely new angle.


* Helpful help

  Naturally it would be extremely tough task to grasp all these
  features at once, thus it is considerably easy to try to do this
  by studying ~Bookmark+~ embedded documentation.

C-x p M-w
