#+BEGIN_HTML
---
layout: post
title: Alpha-radioactive isotope detection
tagline: " in ventilation air on a nuclear power plant"
permalink: /ukraine/zaporizhzha-nuclear-power-plant/alpha-radioactivity.html
categories: [PWR, ZNPP]
tags: [nuclear_thechnology]
---
#+END_HTML
#+STARTUP: showall
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t

* Incident description

  Registration of low alpha radioactivity on the surface of aerosol
  analytic filter after transmission of 0.288E+02 cubical meters of
  outlet ventilation air through it.

* Instruments

  - Automatized system of radioactivity monitoring;
  - Alpha-detectors from the set of 3 different radiometers;


* Method description

  Aeroslols aspiratation of outlet ventilation air on an analytical
  filter 0.2E-04 square meters in diameter with a constant flow 20
  L/minute during 24 hours with further registration of its surface
  pollution by scintillation alpha-detectors.

* Results


  Each sample has initially alpha radioactivity in the range from
  0.8E+00 Bq to 0.17E+01 Bq;
  
  Alpha-radioactivity of each sample has decreased twice in a
  half-hour time.

  Alpha-radioactivity has ceased after 2 days for every sample. 

* Analysis

  Therefore all these measurments are implemented by the set of 3
  different radiometers and they are almost identical in value, it
  might be assumed that it is truly detection of alpha-particles. 



0.864E+05 seconds
