#+BEGIN_EXPORT html
---
layout: post
title: Manage your life
tagline: " by means of Emacs' toolbox"
permalink: /emacs/time-management.html
categories: [Learning Technology, Emacs]
tags: [agenda, time-management]
---
#+END_EXPORT

#+STARTUP: showall
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
* Intro 

  The time itself is a such devious matter thus in most cases bipedal
  blithely avoid to manage it at all. Actually it is so easy just to
  follow the mainstream and check the time once at the New Year party.
  At another hand the time and its amount is a huge crucial part of
  every /productive/ deed: there are tons of time-related chores, habits
  and activities.

* Brief Overview

  For clarity purpose let's imagine two opposite approach to some
  particular time management:

  - 7-days (5/2  9 - 5) rythm;
  - 28-day New Moon cycle;
  - 96-day three-cycle.
  - 
  
** A trivial week

   As the most ancient approaches would ever be. Five consecutive
   weekdays for work with two-days for restoring. Old-fashion and
   effective as an iron knife.

** A single Moon cycle

   Well-known as a women cycle.

** A moon quarter

   As it might be obvious - just free Moon's months in the sequence.


* Prerequisites
** Circadian rhythm
** Sunrise */* Sunset
** Moon phases
** Moonrise */* Moonset
** Seasons of the year

* Initial Approach
