#+BEGIN_HTML
---
layout: post
title: Podcasting as a social intelligence tool
tagline: " pronounce it for yourself first"
permalink: /social_intelligence/podcasting_intro.html
categories: [social_intelligence, podcast]
tags: [pronounce, thinking, audio, transcript]
---
#+END_HTML
#+STARTUP: showall
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
* Intro

  Japanese proverb about sudden pedestrian whisper in the ear.

  Our world over-fulfilled by noisees, and, in opposite lack of
  information. Thus, narrowly speaking, there are an ambudance of
  distorted or even wrong approaches to learning.


  The best one is obvious - be diligent in your studying. Naturally it
  is hard and painstaking chore, but... Just be patient.

  The second best is all around your attention. You should immerse
  your mind in the subject, wiping out all disractions.

  And the third is the last one - just think by your own wit.


* Average usage

* Acoustic requrements

* Repetition technique

* Core idea

# All stuff above should be less than 30 seconds

* Marina

** Just think by your own English

   Nothing at all, just to try do it by yourself several times, perhaps 10 minutes long. Doesn't sound fun?
   Of cause it shouldn't happen in a single night. It might be elaborated and cultivated continuously.
