#+BEGIN_EXPORT html
---
layout: post
title: Manage your life
tagline: " by means of Emacs' toolbox"
permalink: /emacs/time-management.html
categories: [Learning Technology, Emacs]
tags: [agenda, time-management]
---
#+END_EXPORT

#+STARTUP: showall
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
* Intro 

  The time itself is a such devious matter thus in most cases bipedal
  blithely avoid managing it at all. Actually it is so easy just to
  follow the mainstream and check the time once at the New Year party.
  At another hand the time and its amount is a huge crucial part of
  every /productive/ deed: there are tons of time-related chores,
  habits and activities.

  Productivity by its definition relates on time: in general it is the
  amount of your efforts along a some time. It's not surprise at all
  that is a speed, consistency and some times even a rapture to
  produce some unique and ingenious.

  Reasonable to emphasize that relation depending on the main aim of
  your activity - high hopes require a lot of time. So, what if try to
  tame your personal time-table and define it on several hundreds of
  days ahead with a much achievable clarity and order.

* Brief Overview

  For clarity purpose let's imagine three opposite approach to some
  particular time management:

  - 7-days (5/2  9 - 5) rhythm;
  - 28-day New Moon cycle;
  - 96-day three-cycle or a quorter of the year.
  
** A trivial week

   As the most ancient approaches would ever be. Five consecutive
   weekdays for work with two-days for restoring. Old-fashion and
   effective as an iron knife.

** A single Moon cycle

   Well-known as a women cycle.

** A moon quarter

   As it might be obvious - just free Moon's months in the sequence.


* Prerequisites

  Zero prefious experience in time-management and whatsoever.

* Predicates
** Circadian rhythm

   Natural and regular relation among cognitive ability and part of
   the day. Obiously, that its has a peack in the morning, and a
   couple waves in the afternoon.

** Sunrise */* Sunset

   We talk now about the innate bipedals inclination to behave
   themselves depending of the phases of our Sun. There are lurks and
   owls in particular, and them has specific idiosyncrasies related
   with time of the day.

** Moon phases

   
** Moonrise */* Moonset
** Seasons of the year


* Initial Approach
