#+BEGIN_EXPORT html
---
layout: page
title: The Old Quotes
tagline: " are true gold"
permalink: /personal/growth/Plato's-quotes.html
categories: [personal-growth, Plato, quotes]
tags: [become, yourself, wit, wisdom]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil todo:nil pri:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
#+CATEGORY: Plato
#+TODO: RAW INIT TODO ACTIVE | MAYBE DONE CLOSED

* Prelude

Even shallow attention on to a history of human race intellectual
gestation might disclose fact its initialization in the ancient
period. Thurther deduction show up its huge bonds with writing and
literacy, so it defineteley points on one of the most ancient Greek
philosopher ever known, the student of Socrates and the teacher of
Aristotle, - *Plato* (born 428/427 bce, Athens, Greece—died 348/347,
Athens)

* Quotes

** The beginning
is the most important part of the work.

** I shall assume
that your silence gives consent.

**  Wonder is the feeling of a philosopher,
and philosophy begins in wonder.

** Perception and knowledge
could never be the same.

** No one should be discouraged, Theaetetus,
who can make constant progress, even though it be slow.

** It is impossible to conceive
of many without one.

** All that is said by any of us
can only be imitation and representation.

** Friends have all
things in common.
