#+BEGIN_EXPORT html
---
layout: page
title: Stars Warmth
tagline: " between sky and ocean"
permalink: /lit/star_warmth.html
categories: [literature]
tags: [sensuality, sentimentality]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
#+CATEGORY: Writing
#+TODO: RAW INIT | MAYBE
#+TODO: TODO ACTIVE | DONE

* INIT [#C] Prelude                                                 :ARCHIVE:
SCHEDULED: <2022-11-22 Tue .+2d/3d>
:PROPERTIES:
:LAST_REPEAT: [2022-11-15 Tue 08:34]
:END:
- State "MAYBE"      from "INIT"       [2022-11-15 Tue 08:34]
:LOGBOOK:
CLOCK: [2022-11-15 Tue 07:51]--[2022-11-15 Tue 08:02] =>  0:11
:END:

A dusk at early November morning is dense and viscous like a tar. No
wind at all, all are still in a silence soaked with scents
abundance. The grass, leaves, blackberries and soil's odors twisted
with rich aroma of the ocean bay dizzying your mind, but sooth your
soul. The stars gazing at this keep quiet and twinkle one to another.

** Two hares

It was a damp and foggy early November morning. The twilight was so
thick, so you can see below only 20 or 30 meters. I've returned from
the short running session and noticed an adult bunny, sitting on the
road and looking at me from the safe distance. The fence  dense
