#+BEGIN_EXPORT html
---
layout: page
title: Cognitive Biases
tagline: " are human saviour"
permalink: /personal/growth/cognitive_biases.html
categories: [personal-growth, cognition biases]
tags: [become, yourself, thought, contemplation]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 3
#+PROPERTY:header-args :results output :exports both :eval no-export

* Prelude

The recent observations on human behavior enforced me to make
conclusion about their partial self-consciousness as rational
creatures. Popular and wide spreading approach to decision making as
following one's heart, doing what one wants (able) to do and other
peculiar points of view completely displace any reasonable approaches
due to their relative complexity and stochastic nature.

Naturally, who would be interesting to mull over a trivial issue for
several hours or even days and as result achieve a total failure?
It's ridiculous and seems like a silly time wasting.

* What is cognition?

Cognition refers to
#+begin_quote
"the mental action or process of acquiring knowledge and understanding
through thought, experience, and the senses"
#+end_quote


It encompasses many aspects of intellectual functions and
processes such as:

** perception
#+begin_quote
is the organization, identification, and interpretation of sensory
information in order to represent and understand the presented
information or environment. All perception involves signals that go
through the nervous system, which in turn result from physical or
chemical stimulation of the sensory system. For example, vision
involves light striking the retina of the eye; smell is mediated by
odor molecules; and hearing involves pressure waves.
#+end_quote

** attention
#+begin_quote
is the behavioral and cognitive process of selectively
concentrating on a discrete aspect of information, whether considered
subjective or objective, while ignoring other perceivable information.
William James wrote that "Attention is the taking possession by the
mind, in clear and vivid form, of one out of what seem several
simultaneously possible objects or trains of thought. Focalization,
concentration, of consciousness are of its essence."
#+end_quote

** thought
#+begin_quote
In their most common sense, the terms thought and thinking refer to
conscious cognitive processes that can happen independently of sensory
stimulation. Their most paradigmatic forms are judging, reasoning,
concept formation, problem solving, and deliberation. But other mental
processes, like considering an idea, memory, or imagination, are also
often included. These processes can happen internally independent of
the sensory organs, unlike perception.
#+end_quote

** the formation of knowledge
#+begin_quote
the construction, transmission, and contestation of forms of knowledge
#+end_quote

** memory and working memory

** judgment and evaluation

** reasoning and "computation"

** problem solving and decision making

** comprehension

** production of language

* What are cognition biases?
#+begin_quote
are systematic patterns of deviation from norm and/or rationality in
judgment.
#+end_quote

*OR*
#+begin_quote
are rational deviations from logical thought.
#+end_quote

* Why it is crucially to detect them?



* Belief, decision-making and behavioral

**  Anchoring bias

The *anchoring effect* is a cognitive bias whereby an individual's
decisions /are influenced by/ a particular reference point or
'anchor'. Once the value of the anchor is set, subsequent
arguments, estimates, etc. made by an individual may change from what
they would have otherwise been without the anchor. For example, an
individual may be more likely to purchase a car if it is placed
alongside a more expensive model (the anchor).

The anchoring bias, or focalism, is the tendency to rely too
heavily—to "anchor"—on one trait or piece of information when making
decisions (usually the first piece of information acquired on that
subject).

Anchoring bias includes or involves the following:

*** Common source bias

the tendency to combine or compare research studies from the same
source, or from sources that use the same methodologies or data.

*** Conservatism bias

the tendency to insufficiently revise one's belief when presented with
new evidence.

*** Functional fixedness

a tendency limiting a person to using an object only in the way it is
traditionally used.

Karl Duncker defined functional fixedness as:
#+begin_quote
being a mental block against using an object in a new way that is
required to solve a problem.
#+end_quote

*** Law of the hammer, Maslow's hammer (or gavel), or golden hammer

*Law of the instrument*: an over-reliance on a familiar tool or
methods, ignoring or under-valuing alternative approaches. "If all you
have is a hammer, everything looks like a nail."


**  Apophenia

is the tendency to perceive meaningful connections between unrelated
things. The term (German: Apophänie from the Greek verb ἀποφαίνειν
(apophaínein), represent as) was coined by psychiatrist Klaus Conrad
in his 1958 publication on the beginning stages of schizophrenia. He
defined it as:

#+begin_quote
"unmotivated seeing of connections [accompanied by] a specific feeling
of abnormal meaningfulness"
#+end_quote

He described the early stages of delusional thought as
self-referential over-interpretations of actual sensory perceptions,
as opposed to hallucinations.

Apophenia has also come to describe a human propensity to unreasonably
seek patterns in random information, such as can occur while gambling.

The following are types of apophenia:

*** Clustering illusion

the tendency to overestimate the importance of small runs, streaks, or
clusters in large samples of random data (that is, seeing phantom
patterns). In other words:

#+begin_quote
The *clustering illusion* is the tendency to erroneously consider the
inevitable "streaks" or "clusters" arising in small samples from
random distributions to be non-random. The illusion is caused by a
human tendency to underpredict the amount of variability likely to
appear in a small sample of random or pseudorandom data.
#+end_quote
*** Illusory correlation
a tendency to inaccurately perceive a relationship between two
unrelated events.
*** Pareidolia
a tendency to perceive a vague and random stimulus (often an image or
sound) as significant, e.g., seeing images of animals or faces in
clouds, the man in the moon, and hearing non-existent hidden messages
on records played in reverse.
**  Availability heuristic

**  Cognitive dissonance

**  Confirmation bias

**  Egocentric bias

**  Extension neglect

**  False priors

**  Framing effect

**  Logical fallacy

**  Prospect theory

**  Self-assessment

**  Truthiness

**  Other

**  Social

***  Association fallacy

***  Attribution bias

***  Conformity

***  Ingroup bias

***  Other


* Memory

**  Misattribution of memory

**  Other
