#+BEGIN_EXPORT html
---
layout: page
title: Organize Your Work
tagline: " with a minimum interruptions"
permalink: /professional/workflow_inside_org_mode.html
categories: [workflow, org-mode, effeciency, Emacs, Zettelkasten]
tags: [data gathering, data elaboration, notetaking]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export

* Preamble

Without a shadow of doubt the managing your task is a /meta-task/ that
vitally important to accomplish your job in a productive and effective
manner. I mean do it with sincere joy, playfully focusing on each
particular task and, of cause, with minimum silly interruptions. Yes,
it is silly to seek answer on such dumb question: "What I should do
next?" in the morning when you're much productive than ever. So, lets
dismantle several classical approaches to this quite delicate issue:

+ ToDo lists;
+ Time-table;
+ Calendar.

Arguably, but all these tools and a lot more are already inculuded
into the ~Emacs'~ ~Org-mode~ package, and all you're need to do - just
read its documentation. Yes, it is not easy to do, so we are on the
right path.

** Toolset

Separate EWW window for each task  -- does its history also splitted?
Does Desktop-Save saves their properties also?



Separate set of bookmarks for each task

* Average modes

** Task management

Naturally it might be implemented by a single ~master~ ToDo list for
general tasks, and a bundle of ~slave~ ToDo lists, connected and
disconnected optionally, depending on current job properties.

** Data gathering

** Data elaboration

** Meta-analysys

~C-h l~ history of Emacs' commands 

* Notes                                                      :noexport:notes:
 - GitHub.io with Jekyll data representation might be ideal for
   meta-analysys already collected data




