#+BEGIN_EXPORT html
---
layout: page
title: The Cognitive Biases -
tagline: " a set of rigid obstacles to make a thought"
permalink: /personal/growth/cognitive_biases.html
categories: [personal-growth, cognition biases]
tags: [become, yourself, thought, contemplation]
---
#+END_EXPORT

#+STARTUP: showall
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export

* Prelude

The recent observations on human behavior enforced me to make
conclusion about their partial self-consciousness as rational
creatures. Popular and wide spreading approach to decision making as
following one's heart, doing what one wants (able) to do and other
peculiar points of view completely displace any reasonable approaches
due to their relative complexity and stochastic nature.

Naturally, who would be interesting to deeply contemplate about some
trivial issue several hours or even days and as result achieve a total
failure? It's ridiculous and seems like a silly time wasting.

* What is cognition?

* What are cognition biases?

* Why it is crucially to detect them?
