#+BEGIN_EXPORT html
---
layout: page
title: The Best Book I've Ever Read
tagline: "  about Making Money"
permalink: /personal/wealth/money-book.html
categories: [personal wealth, money]
tags: [overview]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
#+CATEGORY: Money
#+TODO: RAW INIT TODO ACTIVE | MAYBE DONE CLOSED

*  Intro

All right, so in this video, I'm gonna summarise some of the insights
from this book, The Millionaire Fastlane.  I thought that this was
gonna be really bad when a friend recommended it to me.  And then this
friend said, "No, trust me. Ignore the click-baity title, The
Millionaire Fastlane, and read the book because it's genuinely really
good.  And it is genuinely really good.  This is probably the single
best book I have ever read on how to build a business that makes
money.  And so in this episode of Book Club, which is the series where
we distil and discuss highlights from some of my favourite books,
we're gonna be breaking down five key lessons from the book.  And
also, the five commandments of building a business that MJ DeMarco
talks about.  How to get rich quick.
*  Avoid the slow lane

*  Work the process

*  Build money trees

*  Switch from being a consumer to a producer

*  Show commitment, don't just show interest

*  1.The commandment of need 

*  2.The commandment of entry

*  3.The commandment of control

*  4.The commandment of scale

*  5.The commandment of time

* Notes                                                      :noexport:notes:
