#+BEGIN_EXPORT html
---
layout: page
title: Organize Your Work
tagline: " with a minimum interruptions"
permalink: /professional/workflow_inside_org_mode.html
categories: [workflow, org-mode, effeciency, Emacs, Zettelkasten]
tags: [data gathering, data elaboration, notetaking]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
#+CATEGORY: Workflow
#+TODO: RAW INIT TODO ACTIVE | MAYBE DONE CLOSED

* Preamble

Without a shadow of doubt the managing your task is a /meta-task/ that
vitally important to accomplish your job in a productive and effective
manner. I mean do it with sincere joy, playfully focusing on each
particular task and, of cause, with minimum silly interruptions. Yes,
it is silly to seek answer on such dumb question: "What I should do
next?" in the morning when you're much productive than ever. So, lets
dismantle several classical approaches to this quite delicate issue:

+ ToDo lists;
+ Time-table;
+ Calendar.

Arguably, but all these tools and a lot more are already inculuded
into the ~Emacs'~ ~Org-mode~ package, and all you're need to do - just
read its documentation. Yes, it is not easy to do, so we are on the
right path.

* A natrual way to make notes

Historically all this fuss around the notes has been successfully
resolved a million years in a row simply inside the one's
skull. Usually _Homo_ just remember what he wants to know in the
nearby future. Yes, this approach has a ton of caveats:

- Longevity;
- Precision;
- Distortion;
- etc.


* A synthetic way of note-taking

Not so far /a literacy/ spreaded across a globe and nowadays in
particular every _Homo_ can read and write. So, literally it might be
implemented by a single ~master~ ToDo list for general tasks, and a
bundle of ~slave~ ToDo lists, connected and disconnected optionally,
depending on current job properties.

 + Task management;
 + Data gathering;
 + Data elaboration
 + Meta-analysys

* Emacs' standpoint

** ACTIVE The Org Agenda

#+begin_quote
Due to the way Org works, TODO items, time-stamped items, and tagged
headlines can be scattered throughout a file or even a number of
files.  To get an overview of open action items, or of events that are
important for a particular date, this information must be collected,
sorted and displayed in an organized way.
#+end_quote


#+begin_quote
Entries in the agenda buffer are linked back to the Org file or diary
file where they originate.  You are not allowed to edit the agenda
buffer itself, but commands are provided to show and jump to the
original entry location, and to edit the Org files “remotely” from the
agenda buffer.  In this way, all information is stored only once,
removing the risk that your agenda and note files may diverge.
#+end_quote

For a much detailed overview each item might be extendeid in a
separate buffer:

#+begin_quote
(‘org-agenda-tree-to-indirect-buffer’)
     Display the entire subtree of the current item in an indirect
     buffer.  With a numeric prefix argument N, go up to level N and
     then take that tree.  If N is negative, go up that many levels.
     With a ‘C-u’ prefix, do not remove the previously used indirect
     buffer.
#+end_quote

** Toolset

Separate EWW window for each task  -- does its history also splitted?
Does Desktop-Save saves their properties also?



Separate set of bookmarks for each task

* Average modes

** Task management

Naturally it might be implemented by a single ~master~ ToDo list for
general tasks, and a bundle of ~slave~ ToDo lists, connected and
disconnected optionally, depending on current job properties.

** Data gathering

** Data elaboration

** Meta-analysys

~C-h l~ history of Emacs' commands 

* Notes                                                      :noexport:notes:
 - GitHub.io with Jekyll data representation might be ideal for
   meta-analysys already collected data




** RAW [#B] Fleeting Notes
SCHEDULED: <2022-02-16 Wed>
:PROPERTIES:
:CATEGORY: Old Notes
:END:

Hide and seek game inside all my projects

Extend key-chords

digital-analogous perceptron

Bookmark+ as a local Wiki

Average checksum in the DrinkMarket store

wys fix on the last pages


odious

одиозный

adjective
 1. одиозный (odious)
 2. ненавистный (hated, hateful, odious, abhorrent, accursed, accurst)
 3. отвратительный (disgusting, hideous, heinous, abominable, revolting, odious)
 4. гнусный (vile, abominable, heinous, nefarious, odious, wretched)

DEFINITION

adjective
 1. extremely unpleasant; repulsive.
    "a pretty odious character"


https://exercism.org/  Programming classes
https://convertkit.com The creator marketing platform
https://boosty.to/mi3ch Critical Thinking on Russian
https://perell.com David Perell
https://readingworldmagazine.com/emacs/2021-11-07-emacs-how-to-find-just-about-anything-on-your-computer-1/


conventional wisdom
spotting bias

     |----------+---------------------|
     | Sequence | Expands to          |
     |----------+---------------------|
     | <s       | #+BEGIN_SRC         |
     | <e       | #+BEGIN_EXAMPLE     |
     | <q       | #+BEGIN_QUOTE       |
     | <v       | #+BEGIN_VERSE       |
     | <V       | #+BEGIN_VERBATIM    |
     | <c       | #+BEGIN_CENTER      |
     | <l       | #+BEGIN_LaTeX       |
     | <L       | #+LaTeX             |
     | <h       | #+BEGIN_EXPORT html |
     | <H       | #+HTML              |
     | <a       | #+BEGIN_ASCII       |
     | <A       | #+ASCII:            |
     | <i       | #+INDEX:            |
     | <I       | #+INCLUDE:          |
     |----------+---------------------|


What is org-store-link?
2022-01-26-zettelkasten.org

Robert Pirsig book

 * Notes :noexport:notes:
section as a set of fleeting notes for further elaboration

Intro
Starting out
Getting better
Unfair advantages
How to grow your audience
Monetisation

** RAW Internal and external
SCHEDULED: <2022-02-16 Wed>
[[info:org#Link Format][links for Zettelkasten]]
