#+BEGIN_EXPORT html
---
layout: page
title: Cognitive Biases
tagline: " are human saviour"
permalink: /personal/growth/cognitive_biases.html
categories: [personal-growth, cognition biases]
tags: [become, yourself, thought, contemplation]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export

* Prelude

The recent observations on human behavior enforced me to make
conclusion about their partial self-consciousness as rational
creatures. Popular and wide spreading approach to decision making as
following one's heart, doing what one wants (able) to do and other
peculiar points of view completely displace any reasonable approaches
due to their relative complexity and stochastic nature.

Naturally, who would be interesting to mull over a trivial issue for
several hours or even days and as result achieve a total failure?
It's ridiculous and seems like a silly time wasting.

* What is cognition?

Cognition refers to
#+begin_quote
"the mental action or process of acquiring knowledge and understanding
through thought, experience, and the senses"
#+end_quote


It encompasses many aspects of intellectual functions and
processes such as:

** perception
#+begin_quote
is the organization, identification, and interpretation of sensory
information in order to represent and understand the presented
information or environment. All perception involves signals that go
through the nervous system, which in turn result from physical or
chemical stimulation of the sensory system. For example, vision
involves light striking the retina of the eye; smell is mediated by
odor molecules; and hearing involves pressure waves.
#+end_quote

** attention
#+begin_quote
is the behavioral and cognitive process of selectively
concentrating on a discrete aspect of information, whether considered
subjective or objective, while ignoring other perceivable information.
William James wrote that "Attention is the taking possession by the
mind, in clear and vivid form, of one out of what seem several
simultaneously possible objects or trains of thought. Focalization,
concentration, of consciousness are of its essence."
#+end_quote

** thought
#+begin_quote
In their most common sense, the terms thought and thinking refer to
conscious cognitive processes that can happen independently of sensory
stimulation. Their most paradigmatic forms are judging, reasoning,
concept formation, problem solving, and deliberation. But other mental
processes, like considering an idea, memory, or imagination, are also
often included. These processes can happen internally independent of
the sensory organs, unlike perception.
#+end_quote

** the formation of knowledge
#+begin_quote
the construction, transmission, and contestation of forms of knowledge
#+end_quote

** memory and working memory

** judgment and evaluation

** reasoning and "computation"

** problem solving and decision making

** comprehension

** production of language

* What are cognition biases?
#+begin_quote
are systematic patterns of deviation from norm and/or rationality in
judgment.
#+end_quote

*OR*
#+begin_quote
are rational deviations from logical thought.
#+end_quote

* Why it is crucially to detect them?



* Belief, decision-making and behavioral

**  Anchoring bias

**  Apophenia

**  Availability heuristic

**  Cognitive dissonance

**  Confirmation bias

**  Egocentric bias

**  Extension neglect

**  False priors

**  Framing effect

**  Logical fallacy

**  Prospect theory

**  Self-assessment

**  Truthiness

**  Other

**  Social

***  Association fallacy

***  Attribution bias

***  Conformity

***  Ingroup bias

***  Other


* Memory

**  Misattribution of memory

**  Other
