#+BEGIN_EXPORT html
---
layout: page
title: The Cognitive Biases -
tagline: " a set of rigid obstacles to make a thought"
permalink: /personal/growth/cognitive_biases.html
categories: [personal-growth, cognition biases]
tags: [become, yourself, thought, contemplation]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export

* Prelude

The recent observations on human behavior enforced me to make
conclusion about their partial self-consciousness as rational
creatures. Popular and wide spreading approach to decision making as
following one's heart, doing what one wants (able) to do and other
peculiar points of view completely displace any reasonable approaches
due to their relative complexity and stochastic nature.

Naturally, who would be interesting to mull over a trivial issue for
several hours or even days and as result achieve a total failure?
It's ridiculous and seems like a silly time wasting.

* What is cognition?

Cognition refers to "the mental action or process of acquiring
knowledge and understanding through thought, experience, and the
senses". It encompasses many aspects of intellectual functions and
processes such as:

** perception

** attention

** thought

** the formation of knowledge

** memory and working memory

** judgment and evaluation

** reasoning and "computation"

** problem solving and decision making

** comprehension

** production of language

* What are cognition biases?

are systematic patterns of deviation from norm and/or rationality in
judgment.

* Why it is crucially to detect them?
