#+BEGIN_EXPORT html
---
layout: page
title: Adaptive Learning
tagline: " don't know what we don't know"
permalink: /professional/double-pondering.html
categories: [Thinking, Pondering, Learning to Learn]
tags: []
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
#+CATEGORY: ThoughtCast
#+TODO: RAW INIT TODO ACTIVE | DONE

The [[https://www.youtube.com/watch?v=83w-jFcwiX0][source]]

* Intro

So you red 30 books last year and you took copious amounts of notes on
everything but how do you actually implement these concepts and figure
out which ones work best in the situations you're in? How do you know
what's effective and what's not? The answer is *double loop learning*.
We can think of double loop learning as learning based on /bayesian
updating/, the modification of goals rules or ideas /in response to
new evidence and experience/.

It might sound like another piece of corporate jargon but double loop
learning cultivates creativity and innovation for both organizations
and individuals.

* Single Loop Learning

Before we get into *double loop learning* let's first look at *single
loop learning*. The first time we aim for a goal follow a rule or make
a decision we're engaging in single loop learning. This is where many
people get stuck and /keep making the same mistakes/.

If we question our approaches and make honest self-assessments -- we
shift into double loop learning. In this stage we assess our biases
question our mental models and look for areas where we can improve. We
collect data seek feedback and gauge our performance, but we can't
learn from experience without reflection. Only reflection allows us to
distill the experience into something we can learn from teaching smart
people how to learn.

* Thermostat Analogy

Business theorist Chris Aguirres compares single loop learning to a
typical thermostat. It operates in a homeostatic loop always seeking
to return the room to the temperature at which the thermostat is
set. A thermostat might keep the room steady but it doesn't learn. By
contrast, /double loop learning/ would entail. The thermostat is
becoming more efficient over time: is the room at the optimum
temperature, what's the humidity like today, would a lower temperature
be more comfortable. The thermostat would then test each idea and
repeat the process. /Double loop learning/ on the other hand is a part
of action science - the study of how we act in difficult situations.

* The Learning Dilemma

Individuals and organizations need to learn if they want to succeed or
even survive, but few of us pay much attention to exactly /how we
learn/ and how we can optimize the process. Even smart well-educated
people can struggle to learn from experience.

We all know someone who's been at the office for 20 years and claims
to have 20 years of experience, but they really have one year repeated
20 times. Many of us are so focused on solving problems as they arise.
That we don't take the time to reflect on them after we've dealt with
them and this mission dramatically limits our ability to learn from
the experiences. Of course we want to reflect but we're busy and we
have more problems to solve. Not to mention that /reflecting on our
idiocy is painful/ and we're predisposed to avoid pain and protect our
egos reflection.

However is an example of the approach we call first order negative,
second order positive. It's got very visible short-term costs. It
takes time and honest self-assessment about our shortcomings, but it
pays off in spades in the future.

#+begin_quote
The problem is that the future is not visible today
#+end_quote

So slowing down today to go faster at some future point seems like a
bad idea to many, plus with the payoff being so far in the future it's
hard to connect to the reflection today. This is the /learning
dilemma/.  Many skilled people excel at single loop learning: it's
what we learn in academic situations, but if we're accustomed only to
success double loop learning can ignite defensive behavior. This is
why learning can be so difficult: it's not because we aren't
competent, but because we resist learning out of a fear of seeming
incompetent.

Smart people aren't used to failing so they struggle to learn from
their mistakes and often respond by blaming someone else, as a
juniors.

* Smart People

Put in their ability to learn shuts down precisely at the moment they
need it. The most in the same way a muscle strengthens at the point of
failure - we learn best after dramatic errors. The problem is that
single loop processes can be self-fulfilling.

* The Problem

Consider managers who assume their employees are inept. They deal with
this by micromanaging and making every decision themselves. Their
employees have no opportunity to learn, so they become discouraged. They
don't even try to make their own decisions.

#+begin_quote
This is a self-perpetuating circle.
#+end_quote

For double loop learning to happen the managers would have to let go a
little allowing someone else to make minor decisions, offer guidance
instead of intervention, leave room for mistakes. In the long run
everyone would benefit. The same applies to teachers who think their
students are going to fail an exam. The teachers might become
condescending and assign simple work when the exam rolls around guess
what many of the students do badly. The teachers think that they were
right so the same thing happens the next semester. Many of the leaders
ajira studied blamed any problems on unclear goals insensitive and
unfair leaders and stupid clients rather than making useful
assessments. Complaining might be cathartic but it doesn't let us
learn agiras explained that this defensive reasoning happens even when
we want to improve. _Single loop learning just happens to be a way of
minimizing effort_.

We would go mad if we had to rethink our response every time someone
asks us how we are. For example so ajiris explains everyone develops
their own theory of action a set of rules that individuals use to
design and implement their own behavior as well as to understand the
behavior of others. Most of the time we don't even consider our theory
of action. It's only when asked to explain it that the divide between
how we act and how we think. We act becomes apparent, identifying the
gap between our espoused theory of action and what we're actually
doing is.

* Stop Getting Defensive

The hard part the first step ajiris identified is to stop getting
defensive instead he advocates for collecting and analyzing relevant
data. What conclusions can we draw from experience, how can we test
them, what evidence do we need to prove a new idea is correct.

* Change Our Mental Models

The next step is to change our mental models break apart paradigms
question where conventions came from pivot and make reassessments if
necessary. Problem solving isn't a linear process - we can't make one
decision and then sit back and await success. Edgier has found that
many professionals are skilled at teaching others yet find it
difficult to recognize the problems they themselves cause. Like
Galilean relativity it's easy to focus on other people.

#+begin_quote
It's much harder to look inward and face complex challenges.
#+end_quote

Doing so brings up guilt embarrassment and defensiveness as John Gray
put it. If there's anything unique about the human animal it's that it
has the ability to grow knowledge at an accelerating rate while being
chronically incapable of learning from experience.

* Habits

When we repeat a single loop process it becomes a habit. Each
repetition requires less and less effort we stop questioning or
reconsidering it especially if it does the job or appears to. While
habits are essential in many areas of our lives they don't serve us
well if we want to keep improving.

* Single Loop

For that we need to push the single loop to the point of failure to
strengthen how we act. In the double loop it's a bit like the Feynman
technique:

#+begin_quote
We have to dismantle what we know to see how solid it truly is.
#+end_quote

One example is a typical: five day nine to five work week. Most
organizations stick to it year after year. They don't reconsider the
efficacy of a schedule designed for industrial revolution factory
workers. This is single loop learning, it's just the way things are
done, but not necessarily the smartest way to do things. The decisions
made early on in an organization have the greatest long-term impact.
Changing them in the months years or even decades that follow becomes
a non-option. How to structure the work week is one such initial
decision that becomes invisible.

* How to Structure

As  G.K.Chesterton put it

#+begin_quote
The things we see every day are the things we never see at all.
#+end_quote

Sure a nine to five schedule might not be causing any obvious
problems - the organization might be perfectly successful, but that
doesn't mean things can't improve. It's the equivalent of a child
continuing to crawl because it gets them around. Why try walking if
crawling does the job, why look for another option if the current one
is working.

A growing number of organizations are realizing that conventional work
weeks might not be the most effective way to structure the work time.
They're using double loop learning to test other structures. Some
organizations are trying shorter work days or four day work weeks or
allowing people to set their own schedule. Managers then keep track of
how the tested structures affect productivity and profits. Over time
it becomes apparent whether the new schedule is better than the old
one.

37 signals is one company using double loop learning to restructure
their work week. CEO Jason Fried began experimenting a few years ago:
 - he tried out a 4-day 32-hour work week;
 - he gave employees the whole of june off to explore new ideas;
 - he cut back on meetings and created quiet spaces for focused work
   rather than following conventions.


37 signals became a laboratory looking for ways for improving. Over
time what worked and what didn't became obvious. /Double loop
learning/ is about data backed experimentation: not aimless
tinkering - if a new idea doesn't work it's time to try something else.

* David Chang

In an op-ed for the New York times Sweeney and Gosvel gave the example
of David Chang. /Double loop learning/ turned his failing noodle bar
into an award-winning empire!

After apprenticing as a cook in Japan Mr Chang started his own
restaurant, yet his early efforts were ineffective he found himself
overworked and struggling to make money. He knew: his cooking was
excellent, so =how could he make it profitable?=

Many people would have quit or continued making irrelevant tweaks
until the whole endeavor failed. Instead, Mr Chang _shifted from
single to double loop learning_. A process of making honest
self-assessments began.

One of his foundational beliefs was that the restaurant should serve
only noodles, but he decided to change the menu to reflect his skills.
In time it paid off: the crowds came, rave reviews piled up, awards
followed and unimaginable opportunities presented themselves. This is
what double loop learning looks like in action: ~questioning
everything and starting from scratch if necessary~!

* Josh Wadeskin

Josh Wadeskin's approach as explained in the art of learning is
similar: after reaching the heights of competitive chess Weights can
turned his focus to martial arts, - he began with ~Tai Chi Chuan~
martial arts and chess are on the surface. Completely different, but
Waights can use /double loop learning/ for both.

He progressed quickly, because he was willing to lose matches, if
doing so meant he could learn. He noticed that other martial arts
students had a tendency to repeat their mistakes, letting fruitless
habits become ingrained: like the managers at jairus - worked with
students grew defensive when challenged they wanted to be right even
if it prevented their learning. In contrast Waitskin viewed practice as
experiment. Each session was an opportunity to test his beliefs.

He mastered several martial arts earning a =black belt= in Jiu-Jitsu
and winning a world championship.

* Conclusion

Ajir has found that organizations learn best when people know how to
communicate. No surprise there:

#+begin_quote
Leaders need to listen actively and open up exploratory dialogues, so
that problematic assumptions and conventions ~can be revealed~.
#+end_quote

A Juris identified some key questions to consider:

- what is the current theory in use;
- how does it differ from proposed strategies and goals;
- what unspoken rules are being followed and are they detrimental;
- what could change and how forget the details;
- what's the bigger picture?

#+begin_quote
Meaningful learning doesn't happen without focused effort.
#+end_quote

/Double loop learning/ is the key to turning experience into
improvements, information into action and conversations into progress.
