#+BEGIN_EXPORT html
---
layout: page
title: Penguin inside Chrome OS
tagline: " is for the initial stage"
permalink: /debian/bookworm.html
categories: [Debian, Bookworm]
tags: [migration, strategy]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2
#+PROPERTY:header-args :results output :exports both :eval no-export
#+CATEGORY: Debian
#+TODO: RAW INIT TODO ACTIVE | DONE

* Preface

* Hard Disk Partitioning

An EFI system partition is necessary to start Debian.

To configure an EFI system partition, go back and select or
create a suitable filesystem. The filesystem must be mounted on /boot/efi.

The filesystem must have type FAT32. The filesystem must be at
least 300MB in size. The filesystem must have flag boot set.

You can continue without setting up an EFI system partition but
your system may fail to start.

* ~ELPY~ as Pythonic *IDE*

** Prerequisites

~ELPY~ has several requirements which ought to be satisfied
preliminarily:

First of all:
#+begin_src python :results output
sudo apt install python-is-python3 virtualenv pip
#+end_src

After that your system is prepared to:

#+begin_src elisp
    package-install pyvenv
  package-install elpy
#+end_src
