#+BEGIN_EXPORT html
---
layout: page
title: Mull Over Your Life's Goals
tagline: " in order"
permalink: /personal/life-style.html
categories: [Personal, Development, LifeStyle]
tags: [order, arrange, life, goal, style]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2



* Life Is Like a Lottery Ticket

A lottery ticket is tantalizing because it just seems so simple
theoretically there's a combination of numbers or scratches you could
put on this ticket. That would unlock literally billions of dollars all
you have to do is get the correct combo and Bam!, just like that your
new life begins. Theoretically the same exists for your life too.


There's probably a simple sequence of moves you could do today: say
the right things be in the right place at just the right time with
just the right people and, - =Bam!= - all your dreams literally come
true. Only problem is you have no idea what these secret steps are
considering the infinite realm of possibilities. It's likely you won't
just stumble upon this without some sort of plan. But, just for a
second, - imagine there's a little blue genie sitting in your ear
whispering to you guiding you each second of your life telling you the
exact step-by-step sequence you would need to do to achieve literally
anything.

But that's basically what planning is right we envision a future. Some
better life for ourselves we strategize the moves needed to get there.
Only problem is most people suck at it using systems that are
either way too basic or way too rigid.

For me getting into Harvard for undergrad y for medical school in
Harvard again for residency was no accident it was strategically
planned and mapped out week after week month after month. What I'm
about to tell you is the closest thing you're going to get to having a
little genie in your ear and with this power you too can achieve
literally anything. To start, let's talk about a commonly talked about
framework


* Four Quadrant System


It goes by many names only thing though there's a huge problem with it.
Let me explain: anything you do in life falls into one of four
quadrants. Quadrant number one is filled with stuff that's both
important and urgent. Sounds great right?

Actually this is not where you want to be. Let me explain most people
start in quadrant one until tired /inevitably falling into quadrant
number four/, mindlessly attending to the non-urgent and non-important
stuff, like cleaning out your email inbox or doom scrolling
Tik-Tok. You goof around here until you're ready to go back to
quadrant number one because guilt or because you've now consumed the
entire internet.

Oh did someone just text you is that a new email in your inbox?
Hooray, you're saved! Can't help but want to look right. I don't need
it! I don't need it!

In your moment of weakness you make a detour into quadrant 3 focusing
on the not important but apparently urgent things and just like this
from quadrant 1 to 4 to 3 to 1. You go running around and around like a
little hamster in a wheel of life, devoid of any growth. Reality is this
quadrant one is just the bare minimum.


* Truth About Quadrant One

Quadrant one is where you go put out fires, but if you're constantly
holding the fire extinguisher. When do you actually hold the hammer.
Furthermore guess where the fires of quadrant one come from. They
ignored dreams of quadrant two, they sprout out from the ground and
come to haunt you like a psycho ex-girlfriend.

You see examples of this all the time:

- Ignore that big project and read the consequences when it's due;
- Ignore quality time with your friends and family and they soon
  become descent strangers;
- Ignore the gym long enough and you'll wake up one day with a heart
  attack.

#+begin_quote
Quadrant two is the /magical fabled land/ where dreams are built.
#+end_quote

You know the stuff that's good for you but because it's not urgent you
never make time for it.


* Box Factory Analogy

Imagine yourself as a =box factory=. A day's worth of work is 50
boxes, but tomorrow the boss says he needs 100 boxes. Uh oh, sounds
/important and urgent/.

Right you don't want to get fired, so, - you grit your teeth and force
it to happen. From simple to-dos phone reminder systems to
micromanaged hour by hour planners your mindset is always the same.

#+begin_quote
Learn another productivity hack to squeeze more juice from each day.
#+end_quote

What if instead of being a ~better worker~ you became a ~better
factory~, instead of just putting out fires every day you spend one
day to make everything fireproof and thus -- /free up the rest of your
life/.

This is what I call the ~factory Boss~ versus ~factory worker~.
Mentality don't get lost in the weeds: strategize at a higher level -
Live your life in quadrant two.

Easier said than done. I know quadrant two tasks are always foggy and
unclear there's no satisfying finish, no urgency and no end in sight.
You can always read more, learn more, work out more and without
inspiration pushing you forward.

_Your brain is hardwired to only do things with immediate rewards_:
things that feel good as chaotic as quadrant one is.


It does indeed feel good checking off To-Do and putting out fires
gives you an immediate sense of accomplishment and thus back to
assembling the boxes. This is the inherent problem. The four quadrant
model gives you the conceptual framework, but it's not practical
instead of fighting your brain's need for feel-good productivity. Build
a system that capitalizes on it.


* Step One: The Secret Quadrant

This is /the crux/a of technique:

- number one: creating the magical quadrant of 1.5.


The secret *quadrant of success* 1.5 is quadrant two's twin brother,
except much sexier. Everything in it is systematically broken down
into task that are not only actionable practical and urgent, but most
importantly of all carefully picked to get the highest yield for your
time.

To create quadrant 1.5 /you first build the cloud/. The cloud
represents your ultimate dream, it hangs in the sky thousands of feet
in the air all fluffy and nice. While you admire this cloud from afar
it taunts you with its tiny little raindrops.

Theoretically, as long as you follow these drops all the way up you'll
reach it. Most people's plans are to do exactly this: follow the drops
from the ground up with checklists, To-Dos, organizers just good
enough to collect the lowest hanging fruit. The few droplets right
above your head you can touch and see the problem is.

The higher you go the more difficult it becomes - how do you know if
you're chasing the right Cloud anymore. Instead do a top down approach
you start with the top of the cloud where the raindrops are incredibly
obvious and fat. You follow them down as they splinter, seeing exactly
what actions should be prioritized.

#+begin_quote
This is called ~building the blueprint~.
#+end_quote

Let's say your dream cloud is medical school studying. The cloud you
see it's actually four key parts grades: medical extracurriculars, a
killer essay and an amazing interview. The interview cloud further
splinters into two key parts: delivery and substance. To deliver your
message well you need charisma a confident voice. And, of course, - a
sexy outfit. We could do an entire series on charisma alone, so I won't
go any further here, but the point is to keep following these clouds
all the way down until you're literally at the level of individual
raindrops.

Done right you systematically understand everything you need to focus
on or prioritize, expose all your blind spots and weaknesses and gain
the ability to course correct. In real time when I was trying to get
into Harvard I remember doing this exact analysis every week. How's my
GPA Cloud doing my extracurricular cloud my, letters of recommendation
cloud and all its tiny mini clouds and raindrops underneath. I was a
pilot and these were the gauges and flight instruments in my cockpit.
They were would tell me if I was on track. Without it I would have been
flying blind. Once you have this blueprint mapped out you begin to
schedule your life around weekly goals.

* Step 2: Smallest Unit of Time

The ~crux~ of technique number two:

#+begin_quote
all goals have a onewe deadline
#+end_quote

This is how you build urgency to everything in quadrant 1½: one month
is conceptually *too long*: knowing you have an entire month to
accomplish something kills any sense of urgency and is too late for
feedback. Having only 12 times a year to course correct is not good
enough. On the other hand one day is *too short* - it creates anxiety
and the desire to excessively micromanage.

#+begin_quote
Hence the weekly deadline for all assigned tasks just /long enough for
meaningful work but flexible enough for you to still handle the rest
of your life/.
#+end_quote

For example let's say you have a medical interview in one month: how
would the weekly goal system work? First week three goals doesn't
matter when you do it how you do it you just have to do it and oh yeah
you only again have one week first goal is to watch five videos on
Charisma. Second goal is to analyze five actors being interviewed,
pretend they are your clients and you are their public relations
manager.

#+begin_quote
Pretend they are paying you a crap ton of money for good feedback so
make sure you know your stuff.
#+end_quote

Third goal is to interview yourself in front of a mirror. After an
hour of this do it again, but this time record it. Watch it and give
yourself feedback.

Second week you have two goals: first is to come up with a list of
life stories and experiences you can sprinkle into your interviews to
show why you are awesome you want these stories to be interesting so
they for sure will remember you. Second goal is to prepare for gotcha
questions - /some smart ass/ is definitely going to ask you about your
top three weaknesses what you regret most. Maybe what your spirit
vegetable is or some stupid thing like that you want to have thought
about some of these beforehand. So you don't freeze in the moment. 

Week three is mock interview time schedule 10 of them with people that
you trust and make it as difficult as possible give them a list of
hardball questions and ask them for real feedback.

Week four - figure out as much stuff about the interview in advance:
where it is, who it is, what makes them tick, read their articles,
understand their field of interest. If their hobby is rescuing
abandoned puppies go rescue an abandoned puppy! So you can relate if
you've noticed.

The mini goals for each week are all actionable steps. These weekly
goals are never outcome based, like get 100 new subscribers or get an
'A' on the exam, but rather something always within your control.

Now that each week's plan is set how do you decide what to do each
day.


* Step 3: Inverted Pyramid Method

Technique number three: _the inverted pyramid method_.

I've talked about this before in a previous video essentially:

- /Always start your day with the most important thing/;
- /Spend the most amount of time on this most important thing and less
  and less time on each subsequent task/.

When done well this entire system works on autopilot. Each week's
goals keeps you flowing forward, while the =inverted pyramid= allows
you to flexibly schedule the day-to-day in service of these goals. The
beauty about the system is that it self-correct: if I haven't made
much progress on a goal becomes that much more urgent as the week
draws to a close.

Elegantly this urgency gets crystallized within the inverted pyramid
too: the more urgent a task, - the more likely it is to occupy the top
tier of importance for the day. This flexibility is the core feature
of this system. +No more micromanaging yourself+ with fancy calendars
or minor systems or detailed To-Dos.

#+begin_quote
Focus on the cloud live in quadrant 1½ and set your weekly goals in
advance.
#+end_quote


* *Summary*

Wake up each day and spend the majority of your time doing your
_highest yield most important activity_. When done right you should
have a clear sense of what to focus on for any given day and that's it
rinse and repeat until success.
