#+BEGIN_EXPORT html
---
layout: page
title: Emacs interaction
tagline: " egronomics"
permalink: /emacs/convenience/cx-mx-ch.html
categories: [Emacs, Ergonomics]
tags: [efficiency, software development]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t eval:no-export
#+TOC: headlines 2
* Preamble

#+begin_quote
*Ergonomics*, also known as human factors or human factors
engineering, is the application of psychological and physiological
principles to the engineering and design of products, processes, and
systems. Primary goals of human factors engineering are to reduce
human error, increase productivity and system availability, and
enhance safety, health and comfort with a specific focus on the
interaction between the human and equipment.
#+end_quote

** Keyboard as the main tool

So, we all are humans, thus we all has a human factor. In particular
case of software development using =Emacs= editor the most efficient
way to interact with your IDE is a keyboard, an old-fashion device
with a hundred of keys at least. Due to this, a number of keys, I
mean, keyboard is an extremely convenient tool to type the text or
commands into your screen.

** Touch typing

An advanced technique of this kind of activity is ~touch typing~, and
it allows to use your keyboard on incredible speed for a while. First
of all you need to put your index fingers on their places: on the
buttons =F= and =J=, for left and right ones respectively. After that
you need to put other fingers on their places as well:

- =A=, =S=, =D= for left ones;
- =K=, =L=, =;= for the right ones.

All preparations are done, just type on the buttons and return your
fingers back at their places. It's definitely not a /rocket science/,
and if you have enough practice it is easy&peasy to type up to 50
words per minute.

* Emacs' commands

* Key-chords

* Frequency

