#+BEGIN_EXPORT html
---
layout: page
title: Mechanical Approach
tagline: " does not work for humans"
permalink: /generic/human_nature.html
categories: [Philosophy, Thinking, Iain McGilchrist, Intellect]
tags: [brain, hemisphere, thought, thinking]
---
#+END_EXPORT

#+STARTUP: showall indent
#+OPTIONS: tags:nil num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t
#+TOC: headlines 2

The [[https://www.youtube.com/watch?v=REB7GOxX5Mk][source]]

First of all can you hear me. Am I switched on at least technically
switched on good well it's a great honor to be invited to speak here
at Duke and to give the John P mcgaven lecture um I'm I've been very
kindly welcomed here and I will do my best to convey something of the
magic that I feel around the subject that I've chosen to study for the
last few decades.

In the third Century the philosopher Plato asked the fundamental
question, but we who are we a searching question especially in our
times when no one seems to have the foggiest idea who we are what the
world is and what we're doing here. And it's a particularly important
question for anyone involved in the professional care of our fellow
human beings.

There are many ways to approach an answer to this question but one of
the most important right now is the seemingly obvious apophatic answer
we are whatever machines are not however much people may be led to
believe that we are machines. It remains a *fundamental error*.

It has often been said with considerable insight that medicine is as
much an art as a science, and goodness knows it's very much of both.
It's the most fascinating of all sciences. The science of conscious
beings capable of having souls. It is also uniquely positioned in the
humanities as the way of understanding and responding to humanity's
flesh and blood.

Perhaps it's fitting that I came to the practice of medicine by a
circuitous root or it may just be an aberrant gene as my father was a
physician and so was his father. My father even tried not to become a
doctor but it was no use, and I too failed dismally to avoid the
Fate. I started out with a family prejudice in favor of science both
my grandfathers were scientists and I was encouraged by them to
immerse myself in science, but since my teens my greatest
preoccupation has always been with philosophical questions. And
science as I was taught it seemed to ignore them and instead major on
technical matters.

I made my escape into the pen arms of the humanities where I was
enwrapped by everything I learned. I went to Oxford and studied
literature. My first choice philosophy being wedded to politics and
economics, neither of which had the slightest allure for me.

How I came to medicine is a slightly unusual and somewhat
philosophical path. I had been studying literature and I wrote a book
about it my experience called against criticism, which if you're in
the field and have a secure academic career ahead of you is called
shooting yourself in the foot, but in any case I wanted to
express what I found was wrong with the way in which we approached
literature.

And to cut a very long story short I thought that what had happened is
that living human beings before us had left organisms behind Aristotle
calls the work of art an organism so something like an individual
person that was birthed by an individual person and speaks to me an
individual person. And this thing was both unique in that it couldn't
be replaced by anything else in the /Cosmos/. It was implicit.

In other words all its power and meaning came from the way in which it
made things present to us implicitly whereas if they're stated
explicitly they become nothing. So for example when Hardy was bereaved
in 1912 he wrote These wonderful poems 1912 and 13 on the death of his
wife you may ask me what what do they say? Well they say that when you
lose somebody you love it's very painful, but I can hear that down the
pub every night, but that's that won't substitute for his poems which
are absolutely brilliant, unique expressions that bring so many things
together in a way that explicit language can't.

And the third thing about them is that they were /deeply
contextual/. In other words they were everything I believe is altered
by its context. Sometimes I tell a joke about American serial packets
which goes like this there are four sizes: one is =Jumbo= which means
very large then there comes an =Economy= which means large, then there
comes =Family= which means medium and finally there is =Large= which
means small. So context can change anything's meaning depending on what
surrounds it.

#+begin_quote
And since everything is what it is only by the connections it makes
with everything else.
#+end_quote

We don't live in a world of bits that have to be put together - we
live live in a world that is a seamless flow of connections and things
that stand out in it we call a thing. I noticed that thing and that
thing but they all live in that connection. So I was unsatisfied with
this - I wrote this book and I left the world of englit and all that
because I realized that the problem was the ~Mind---Body problem~ and
I went to all the philosophy seminars and I just thought the
philosophers are just too disembodied in their approach.

I wanted to do this must do it in a more embodied way and around that
time Oliver Sacks had published ~Awakening~ which seem to me a model
of how medicine should be done respect for the individual seeing and
reproducing for the reader /the quiddity of the individual/, but also
being able to see along with that individual.

/Various great general truths/ about the way the brain and the
personality and the lived life relate and so I set off on the long
process of. Being a first year medical student and working my way up
and then becoming a qualified doctor and doing work in neurocenter and
then went to the Morley Hospital in London, which is a big training
ground for psychiatrist and also has a neurosurgery and neurology arm
to it.

And I was intrigued I won't go into the whole story, but I was
intrigued by some things I heard about hemisphere difference. I've
been told of course as all of you

#+begin_quote
have been told that everything to do with hemispheres is /rubbish/
because it was all /pop psychology/ and it was exploded in the 1990s at
least, but because we got the answer wrong saying that the left
hemisphere is reasonable and reliable and down to earth and
unemotional and the right hemisphere is sort of all over the place.
#+end_quote

But basically deals in pictures uh this is very wrong: the left
hemisphere is not reliable - it's profoundly unreliable. In fact I'm
not the only person but at least two other neuroscientists I know have
called the left hemisphere /on its own deluded./ And in fact the
syndromes in which delusions manifest themselves and there are many
fascinating ones and I go through them in the first part of the matter
with things are almost always caused by deficiencies in the right
hemisphere, - /almost never by deficiences in the left hemisphere/.

So what we what we needed to do was to look at these differences in a
new way again.

To cut an extremely long story short what I came to real. And this is
not contested by any NE neurologist I know of anywhere in the world is
that the difference is one of attention, - so after a right hemisphere
stroke patients are often said to have a pathological narrowing of the
window of attention, but more than that they have a particular use of
that attention which is to get things so they're intent on getting
things controlling things.

And they see only things that stand out as objects of use maybe to eat
maybe to build shelter maybe to make a tool it doesn't matter but
after all the right hand the left hemisphere's tool is the one with
which we manipulate things, and we grab them and we get them.

So important is that that all neuron neurological networks, neural
networks that we know of going back 700 million years to nematostella
vectensis =anemon= living off the Isle of White. All of these networks
are asymmetrical. Why and why on Earth would they develop into
separate substrates? For ~consciousness~ as they have done in higher
animals.

There is a band of fibers at the base of the brain called the ~Corpus
Colosum~ only 2% of neurons actually cross it of. Their message is
inhibition: they are functionally inhibitory. And I wondered what this
was about. It seemed that two things needed to be kept apart and just
to add a little icing to the cake. There wasn't a ~Corpus Colosum~
until mammals came along - the hemispheres were just separate. So
there's something here that required answering, and I started to
research into what the real differences were and in a way they devolve
on this question of attention.

And I didn't immediately understand how Central that idea here is how
very important! It is I just thought I'd been trained to think of
attention as another cognitive function but hello it is not, it is -
the way in which we dispose our consciousness towards the world.

And it makes a huge difference both to what we find in the world and
to who we are, we who do the attending it changes the phenomenological
world. So if I may summarize very very briefly the sort of differences
in the phenomenological world sustained by the left hemisphere and the
right hemisphere it's something like this.


So remember the left hemisphere is looking for a thing that it wants
to grab quickly and deftly and use so its intell its attention
produces a world full of things that it already knows what they are.
And it knows that it needs them things that are certain and fixed for
the time being static frozen, so that they can be grabbed quickly.

Explicit abstracted from Context disembodied general in nature and
reduced to its parts because it's fragmenting whatever it looks at the
holes.

That are the only things that really exist are always fragmented into
parts, and we use the word part because we're used to, looking at
machines, but really parts are only holes at another level of vision.

So what's the right hemispheres work ~World likee~ pretty much the
opposite of this a world in which everything is fresh unique never
fully known never finally certain but full of potential.

You could say the left hemisphere narrows down to a certainty the
right hemisphere opens up to a possibility - it understands that
context changes everything. All that is implicit that nothing is ever
merely static and unchanging, /but flow and radically
interconnected/. It understands the parts are the left hemisphere's
invention and its world is an animate one.

You can investigate this now quite painlessly by using a technique
called transcranial magnetic simulation which depending on the
frequency of the impulse can either suppress or enhance the underlying
cortex. And if you suppress areas of the left hemisphere princi the
left frontal lobes and the right and it enhance the right frontal lobes,
but also the right temple parial region you get people who see things
that we would normally consider merely inanimate as animate.

For example the sun moves across the sky brings warmth, and
relationship whereas they may see if the opposite happens. And the left
hemisphere is enhanced - they may see people as machines or zombies.

And that of course is one of the ways in which now a lot of
philosophers, scientists and public figures to speak about the human
condition.

And the final thing, I want to draw attention to, is the left
hemisphere looks only at a representation. A representation means
presented again after it's actually no longer present. So the right
hemisphere sees the is aware of takes in not just sees, but allows to
come into being something for us that is a living world and almost
immediately our left hemisphere was taken over and said oh I
understand that picturesque landscape that you're looking at which
initially inspires or it's a picturesque landscape I put it in my box
of romantic pictures.

So it's very difficult for us to escape this categorization that the
left hemisphere produces and effectively - it's producing a map
there's nothing wrong with a map. A map has very little information
about the world in it, very, very little, but that doesn't make it a
bad ~map~. That makes it a good map if it had too much information it
would be useless. So we need a map, but the mistake is when we believe
we live in the map!

And I would say that's where we now are.

So attention changes the world. It really does there's a mountain
behind my house. Its name in Norse means the ~Sloping Rock~. What that
tells you is that Norse men coming down about the year a thousand down
that part of Scotland used the sloping outline of the mountain behind
my house as a landmark. That told them here was was a ~Treacherous
Bay~ but the PS who lived in the shadow of the Mountain. For them
it was the home of the Gods as well as physical shelter from storms.
And in the 18th century people came there and drew it for them.

It was a many colored many textured form that was very beautiful. In
the 19th century people got more interested in geology and it just
happens to be an exceptional example of columna Bassel formation.

In fact it's contiguous with the Giants Causeway in Ireland a straight
line that runs across and that's where that formation comes into the
world. For a speculator therefore it's dollars. Dollars for physicists
it's 99.99% empty space and the other 0.01%

We don't really know what it is now, which of these is the real
mountain. None of them is the real mountain. They are all real they are
just the products of different takes.

And if you take a clinically detached view of the world you become a
very sterile isolated person who finds it very difficult to relate in
any kind of deep empathic way with life, and its sufferers who are all
around us. So attention has the nature of love in fact.

Lou lvll early 20th century French philosopher said precisely that
that love is a pure attention to the existence of the other. And Simone
V said that it was the rarest and purest form of generosity. And that
what people crave is in fact attention as much as anything.

It is a form of love but it has very down to Earth application. So as a
psychiatrist I made sure I had no computer on my desk. I took
discreetly handwritten notes and patients sometimes said: how lovely it
is to talk to a doctor who's not staring at a screen.

There were problems with checklists with structured questions because
they seem to the patient unreal, they seem mechanical, they seem as
though you're not really paying attention to them, - you're just trying
to fit them into a box you've already decided on. And so I think
there's great risks to all. These things and speaking of risk in the
profession of a psychiatrist that has to be a risk assessment,
because everybody's dead frightened of being sued and if you haven't
done a risk assessment you're vulnerable.

But we now know from research that they are 100% useless, - they are
no better than anybody's guess and yet we carry on doing them and
making people feel less than human.

My risk assessment tool was an untrained nurse who'd been on the ward
for 40 years and had very good insight into people and she just say:
"I'm not very happy with Mrs S. this morning and I'd go and see her"
She was dead right. What then is a doctor when my grandfather was a
doctor there were only six effective cures in his medical armentarium.
Rather than giving out potions, he and his fellow doctors ministered to
their patients and they gave of themselves to heal literally. Means to
make whole. And heal, hail, whole and holy all come from the same root.


There's a message there in the US medicine is a second degree which is
more sensible than in Britain where you can embark on medical training
straight out of school if you have the right high qualifications in
chemistry and biology and before you really know anything about life.
But most often those first degrees are I believe in science I think.

Ideally all practicing Physicians and surgeons I.E those who are not
merely research orientated but deal with real suffering people should
ideally have a background in philosophy or literature.

#+begin_quote
Too many doctors are amazed and even seem a little hurt at the very
idea that the body is not a machine and a patient is not a faulty
mechanism.
#+end_quote

Believe it or not in the Royal Institution Christmas lectures for 2013
the UK's Flagship science series according to its website aimed at
aspiring young scientists. A distinguished Oxford biology lecturer used
the very specially human Act of two people gazing at one another to
impress on her indeed impressional audience of 11 to 18 year olds.

That you're amazing we're all amazing because we're all hugely
complicated machines. Perhaps it had slipped her mind that machines are
not social beings that they don't have ~consciousness feelings~,
personality, will or individuality, that they have no appreciation of
music, dance, poetry, art or nature, that they do not fall in love and
have no sense of humor, and they do not have the ability to change
their minds, and have none of our capacity to sorrow over the past or
project a delighted future. And that's not even taking into account the
far more complex issues entailed in human consciousness including:

- imagination;
- morality;
- creativity;
- the capacity for ~spiritual awe~ and;
- allegiance to beauty truth and goodness.


And in case that should sound the slightest bit rarified I'd like to
mention that they don't have bodies either and they do not die.

It is true of course that you're amazing, we're all amazing but it's
precisely because we're not just hugely complicated machines. If we
carry on talking like this to the aspiring young we will get no better
scientists than we deserve.

#+begin_quote
In reality nothing in the entire universe is like a machine except the
few lumps of metal we have made in the last few hundred years.
#+end_quote

And that may surprise people, but neither the /inanimate World/ nor
the /animate world/ are well explained by thinking of them as machines.


Philosophy is intrinsic to science and I'm afraid that philosophers
rather look down on science as though they didn't have anything to
learn from it. This is a big mistake and scientists rather neglect
philosophy because it will slow them down on their race to the next
discovery. And perhaps an honor, but they were never originally
separate.

Until the term science started to be used in the word sense it's now
used about 1830. Science simply meant knowledge and it still that's its
central meaning. And the philosopher ~Whitehead~, who I think, is
probably the most important philosophical voice in the last 100 years
says:

#+begin_quote
The antagonism between science and metaphysics has like all
family quarrels been disastrous.
#+end_quote

So there's been an impoverishment of Science and philosophy by the
estrangement now in physics that changed a 100 years ago about 1890.

People thought physics would have to fold up shop, because they
discovered everything that was going to be known and there was nothing
more to do. Then suddenly a bombshell dropped: /nothing mechanical
about the the inanimate Universe/ at all, and this meant that
physicists had to open themselves to philosophy in order to understand
what they were seeing not so much.

In biology though John Haldane and his son JBS Haldane as well as
Conrad H Wadington and Ludwig Fon Bolany saw that organisms were
complex systems that is not the same as a complicated machine not just
a kind of clock not just a ser Al operating series of stimuli.

It was a very complex system in which there were reentrant
self-referring loops and in which intrinsically we couldn't know the
outcome not because we didn't know enough yet but because it was
actually impossible to know precisely to determine exactly what that
system would end up doing. But molecular biology which arose around
the time at the end of the war turned the block clock back and life
scientists saw themselves as engineers.

Now the highly distinguished microbiologist KL wo whose work
revolutionized biology wrote: 

#+begin_quote
Biology today is no more fully understood in principle than physics
was a century or so ago.
#+end_quote

In both cases ~The Guiding Vision~ has or had reached its end and in
both a new deeper more invigorating representation of reality is or
was called for a society that permits biology to become an engineering
discipline that allows that science to slip into the role of changing
the living world without trying to understand it is a danger to itself.
and he concludes:

in a resonant image molecular biology could read notes in the score
but it couldn't hear the music now this is an exciting time for
biology I believe um there are a few uh spirits who are very much at
the Forefront in their field and I particularly mention here Michael
Levin a developmental biologist at tus University who is a very
hard-nosed conventional scientist but has been forced by his
researchers to realize that we don't understand a great deal about how
organisms work somehow the very notion that an organism even a single
cell could be likened to a machine is impossible a single cell
organism and this was something that Barbara mlin talk realized going
back to the 70s and 80s and she received a Nobel Prize for her work
the single organism can develop an intelligent response to a crisis
that it cannot be prepared for either by Evolution or by that cell's
previous experience and this is immediately brought online not two
billion years later uh after random things have been tried and
eventually we find the answer no it h the crisis happens on Thursday
on Friday there's the answer now this is exciting and important and it
suggests to me as it does to Michael Lan and to many other biologists
now such as James Shapiro at Chicago that single cells have
intelligence if intelligence is being able to find a novel way to
answer a hither to unknown problem and there are lots of examples this
it's very obvious in Plants but it's also as I say obvious going all
the way down to a single cell and just to mention some of the ways in
which life is nothing like a machine you can switch a machine off and
you can hope to start it up again 5 years later you can't do that with
a living life also we model machines on systems that are very close to
equilibrium dynamic equilibrium and that's one of the reasons why they
can be switched off and restarted but life is always at a very long
way from dynamic equilibrium and it is not in stasis as a machine is
until set in motion everything living is always in motion and we think
that the cell for example is static because we used to seeing diagrams
in textbooks and microphotographs but if you actually look at a cell
and you can see the membrane almost disappearing and then reappearing
again things going in and coming out all the time and this is a thing
that is constantly changing in fact metabolism literally means change
and we can't stay the same without metabolism and and yet metabolism
is Chang this takes me back to a saying of my all-time favorite and
most esteemed philosopher heraclitus a pre Socratic philosopher who
said by changing it remains itself and that is really a succinct uh
version of what biologists are now discovering 2,500 years later also
there is nothing about a cell that is nonlinear understanding seems to
come top down as well as bottom up an organism and its environment are
not like a machine in its environment they're not just in some form of
interaction not even a two-way interaction but interdependent Mutual
Constitution so the organism and its environment don't just take it in
turns to ping pong backwards and forwards the the bowl of
consequential action the the the environment and the organism become
what they are in interdependent Mutual Constitution and the parts of a
machine are not continually changing that would be hopeless but in an
organism what we call the parts are constantly building themselves
remodeling themselves and so forth and they only come into being out
of that embryo by differentiating themselves from everything else not
by adding in a part in any way uh they also unlike machines organisms
have imprecise boundaries and they engage in bootstrapping I.E uh no
machine can generate a code by which it can be constructed at the same
time that it itself is coming into being it requires the code to being
already constructed the the instructions to be there for it to be made
but but organism are not like this organisms come into being and
generate meaning generate structions for their own building as they
are being built by themselves and you know we now after the heroic
effort of decoding The genome we are faced with the fact that there is
almost nothing in the genome it's 98% of it is what we call junk DNA
which just repeats sequences I I suspect that we'll find later that
it's not junk in any sense but there we are but the other 2% can't
possibly account for all the complexity of constructing an Oran
organism in uh human gestation uh in the mother's womb a baby develops
every minute on average a quarter of a million nerve cells a quarter
of a million every minute now those nerve cells are not all the same
of course they all go in different places if you look at the structure
of the brain in any detail you'll realize that there is an infallible
plan here almost infallible plan too infallible because nature likes
to work with a little uncertainty otherwise it would get stuck there's
always a little bit of change but generally a degree of Conformity to
a plan but where is that plan where is the the imprint that tells the
brain what a brain should be and with certain kinds of worms you can
cut the head off you can cut cut it off hundreds of times you can have
the same same body generate a new head and every time it generates a
new head it has all the memories that the original head that's now
been incinerated had how so beyond all this we need to be thinking
about science in a way different from the way we do Humanities provide
the essential context for science especially the clinical Sciences the
success of the Machine model and it needs to be given due honor they
treating things as mechanical has resulted in great discoveries but we
make the illicit jump from that that what we're dealing with is a
machine so in a complex system we can have something so massively
interconnected and related that you can't possibly understand how it
works but if you if you focus down on a little tiny part of the
picture you can see one Arrow leading to another arrow leading to
another arrow now our interventions are at that level we take a a
micro step we change something and it has a result that we can predict
but that doesn't mean that the thing is at all like a machine it's not
a complicated system it's a complex system whether one goes upwards or
downwards in scale one finds that machine thinking no longer suffices
there's a tradeoff between truth and utility which is also that
between the dispositions of respectively the right more veridical but
more complex and left less veridical but simpler hemispheres we are
nothing like machines then even when viewed from the outset sorry from
the outside it's also that the interiority of the human subject cannot
be excluded from the picture this however is something that science
for entirely understandable and useful reasons forbids so science can
do much but little at all in bringing us to an understanding of a
human life science is based on the idea that we're not going to take
into to account purposes or values and that's a perfectly legitimate
thing to set out as the basis the axioms from which you work but it's
no good at the end of that saying we pronounce that having looked
everywhere we find no purpose and no values I mean that would be like
a policeman stopping the traffic in the street and then writing
solemnly in his notebook the silence in the street is very suspicious
so this is the problem all is in process we are processes that flow
indeed as heraclitis said everything flows and we are whirlpools in
the Stream So I see each living being as being like a whirlpool in the
Stream for a while it's there you can photograph it you can measure it
it can move Stones it's real but after a while it moves on now was the
world poool in the water absolutely not it wasn't in the water in a
way a ball would be it is the water it's just the shape the water
takes for a while and then the water moves on and the water is still
there and that is who we are we are world pools that are for a time in
the Stream and we have our day as it were as a whirpool and then we go
into the larger flow again there's a contrast here between a world of
pieces that are static and separate on the one hand and a world of
flow and seamlessness on the other where there's no such thing as
stasis and division only relative stability like that of a river and
relatively distinct features such as the edies in the Stream or the
waves in the sea David Tong professor of theoretical physics at
Cambridge writes I see no evidence whatever for discreetness all the
discreetness we see in the world is something which emerges from an
underlying Continuum so if you're saying there is a hierarchy here at
the base there is only the continuous but the whole business of the
evolution the cosmos is making distinctions this idea of multi
multiplicity within Unity gives rise to a different understanding of
death it's not that the machine stops it's that the water moves on why
are we so afraid of death my view is that there are only two
possibilities either there will be nothing or there'll be something if
there's something I'll be fascinated to know what it is if there's
nothing I won't be there to be disappointed say it's not something to
fear Mary Midgley a philosopher who was both a friend and somebody I
greatly admired lived to Great old age about 96 and when she was 92
she wrote a thing saying I don't worry about death at all when you
think that you might be condemned to a universe in which you could
never get rid of yourself you would always always forever and ever and
ever be yourself it's appalling and it it sets sets up fear in the
heart and so the question is only when and I think the normal portion
size is about right having reached it and being living on borrowed
time and so I see Life as a gift any more time is good and if it isn't
then fine by me we live in a world in which quality is no longer the
important factor quantity is but quantity is a very bad um guide to
what is valuable and I say this death is not the opposite of life but
it's end and fulfillment the opposite of life is not death and not
even inan animacy it's me mechanism and here I refer I haven't got
time to explain this to the uh biologist and mathematician Robert
Rosen who wrote a book called life itself and a slightly more
penetrable book called essays on life itself but but his General
thesis is that there is no huge divide between the inanimate and the
animate but the inanimate is a version of things that does what life
does but very very very slowly and only to a tiny agree so things in
the inanimate World respond to forces and they move and they change
and they develop but what life does is both do this billions of times
faster but also to a very much higher degree it can respond to value
and I believe the ground of being is whatever it is part of that in
ontological primitive are values such as Beauty goodness and truth and
the reason there is life which is a very costly process if you ever
ask yourself why there should be life at all is in order to respond as
Whitehead said if you want permanence the secret is never to have been
alive a rock can live for millions of years once you have life it's
both very expensive in energy and it doesn't last that long there are
actino bacteria at the base of the ocean single examples of Rich are
half a million years old so if evolution is all about achieving
permanence it hasn't gone the right way about it instead I believe
it's about resonance responsiveness the business of relation I believe
the whole everything that exists is primary relational and that's not
a an extremely Outsider position I believe that relata are the product
of relations not the source of relations anyway I I'd love to talk
more about that but I can't medicine's not only about bodies but about
people immediately we're outside the field of science alone nor are
bodies for that matter simple at all and matter is not simple at all I
always say materialists at least the ones that believe that it's got
nothing to do with Consciousness are not people who overvalue matter
they are people who undervalue matter after all if you take the really
hard-nosed position that matter has nothing to do with Consciousness
it's something very remarkable because after a few million years it
gives rise to bark and Matthew passion that means that matter pure
lump and matter that you've defined as having nothing interesting
about it does some very interesting things you haven't solved a
problem you've just specified one so core to being human is attention
and intention machines can neither at tend nor intend the greatest
influence on John mcgaven was the Canadian physician Sir William Osler
and he was an important figure in my medical education too and his
most important Legacy was the insistence that students learn from
seeing and talking to patients and the establishment of the medical
residency that is to say the doctor literally living in hospital
alongside the patient his best known saying was listen to your patient
he is telling you the diagnosis in my day in medical school machines
were considered tangential we were taught to pay attention to listen
carefully to the patient's story and ask questions to observe and at
that point we should have made the diagnosis only then should we lay a
finger on the patient in order to confirm what we suspected was the
case and investigations came last of all solely to firm up the
diagnosis for the notes so solving problems is not exactly what we're
there for a machine can be fixed but a person can't be fixed a
computer can solve a defined problem but most human problems are not
that easily defined at all relationships including the doctor patient
relationship are essential to what is going on in medicine whether you
realize it or not so uh no computer can undoubtedly Aid a s s surgeon
there it is rightly treated as what it is a tool it's non-relational
it has no emotions no body and cannot suffer or die but awareness of
all this is at the very core of Medical Practice relationships as the
sin quona fulfillment in life are important with three main elements
and we we know this from a mass of sociopsychological research the
three things that make people feel fulfilled and make them happy are
the sense of belonging to a coherent society that shares beliefs and
practices and that they can trust and share their lives with that's
the first the second is closeness to Nature not going for a walk with
headphones and improving your physique and looking at your phone but
actually just being there and for one moment to be just aware of the
wondrousness of what it is you're looking at and the third is with the
spiritual realm I'm sorry for those people who think something
terrible about the idea of spiritual life I can't help but I'm just
reporting the evidence don't shoot the messenger the evidence is
stronger on the last of these than either the other two but they're
very important and they have effects on the whole of Life
psychological life of course but also physical health so in fact
belonging to an Engaged community of people who worship together is
more effective than losing weight stopping smoking and going to the
gym three times a week not that you shouldn't do those things I'm sure
but I'm just pointing out that life is not as simple bodies are not as
simple as we sometimes assume and the these effects are on all both
cognitive emotional moral and physical life our fragmented life
denying grasping culture is making us sick sicker than we have ever
been and if we're to heal and make whole again something very
different is required as Einstein said we can't get out of the crisis
by the same kind of thinking that got into got us into it in the first
place so we've been commodified and commercialized by a capitalist
Society curiously here there is a toxic alliance between capitalism
and bureaucracy both hate one another but they're both doing the same
mindless left hemisphere work both in their different ways driving
utility alone and as Ling pointed out in the 18th century those who
believe in utility have to answer the question utility for what if the
answer is just more utility you have a problem it's got to be utility
for something Beyond utility that might be something like I suggest
goodness Beauty truth all the sense of the Sacred things that have
disappeared from our lives with devastating consequences it's
pretended now that doctors teachers nurses clergy provide a product
rather than embody sacred duties towards others hence it is that their
expertise must be replaced by blind rule following and their codes of
Ethics which no machine could understand replaced by administrative
procedures unfortunately administrators don't seem able to understand
that either to allow otherwise would to admit that mechanism is not
everything and that people in their lives cannot be as they say
operationalized without loss how grave those losses are we only
beginning to recognize we have worse to come I fear at the very least
if we carry on relying on machines doctors and healthc care workers
will become deskilled patients will be disaffected and they will be
overinvestigation scanning normals leads to chance findings we often
find lumps and bumps and growths and when you don't know what they are
you're obliged to investigate them most aren't cancer but they lead to
investigations biopsies even operations which are always unpleasant
sometimes harmful and occasionally fatal this process leads not just
at time to physical harm but to false reassurance and inevitable
anxiety and although Daniel K caraman suggests that skill in
professionals is overrated I take his evidence to Pieces clinically in
the matter with things and I'm sorry to report that the papers that he
sides say nothing like what he takes them them in he probably hasn't
looked at them for about a long time and they say in most cases
exactly the opposite they are in Praise of the developed skill of a
professional and the draes have written about this that there are
different levels of skill in the first three most primitive levels
having an algorithm helps you but when you get to be an expert having
algorithms actually impairs your ability to do the job and so we end
up with mediocrity instead of excellence and this is true of Pilots as
it is of surgeons and unfortunately science is important and entirely
legitimate claims on Truth risk being compromised if they're hijacked
by the left hemisphere refusal to acknowledge the limitations of its
chosen model of representation here the Machine model so how can we
move forward how would a paradigm shift for example towards a model of
a human as part of the ever moving shared stream of life changed the
way we thought of ourselves influence in other words how we answered
plotinus's question who are we it would change the way we relate to
one another to our ancestors and to our progeny to past and future
Generations as well as the wider World human and non-human in all its
complexity the world where we live out of which we arose and to which
we return but it would also quite simply help us avoid viewing
ourselves as machines the most crippling possible Distortion of what
it means to be a human being any astute clinician knew long ago that
our attempts to view complex biological systems of machines was a
dangerous delusion but now even researchers realized that the model
has signally failed unfortunately our errors are compounded by the
fact that scientific research into the human being and specifically
into the brain is almost exclusively carried out using the model and
the language of the machine neuros speak is replete with references to
wiring circuitry modules switches signals data banks inputs outputs
into the brain en coding Computing and having mechanisms of every
conceivable kind and no one knows better than I do from personal
experience how hard such terms are to avoid given the existence of the
culture yet Wendel Berry is surely right when he says that we should
banish from our speech and writing any use of the word machine as an
explanation of or definition of anything that is not a machine the
language use is hugely important it it determines what we can
understand and there's a lovely passage which I haven't got time to
read from the physicist David merman who uh independently as a
physicist says what I from a philosophical point of view say which is
that relations are prior to relata he actually uses those very words
but he points out that the writing of science has become become
incredibly tedious abstract impersonal and such that only somebody
with an extraordinary willingness to endure endless tedium can read
their way through scientific papers now but in the 19th and early 20th
century scientists wrote beautifully and personally about their
findings and anyway I've spent a lot of time reading and translating
The Works of neuros psychiatrists in the 20th century in the first few
Decades of it French and German and in them lie much of the Gold Dust
for those of you who really un want to understand the relationship
between the brain and mind so partly the problem is the neoplastic
growth of reductionism in science and partly the surgical excision of
adquate Education in the humanities at school which might have helped
sophisticated not just writing skills but insight into what we're
actually doing when we practice medicine so let's go forward with a
few resolutions for a future medicine that's both more human and more
Humane let's begin from education we're fallible human persons dealing
with the fallible human person knowledge of great human achievements
in the humanities and some knowledge of history and philosophy would
not only make us better at understanding human life and human
suffering but bring a reliable lifelong source of sustenance when we
may be spiritual starved or distressed not unimaginable episodes in a
physician's life it would also induce a certain humility that would
issue in being better Physicians we have expertise but expertise is
being denigrated it's not mechanical rather the fruit of hard work
intuition and experience and though our expertise importantly includes
much information it goes well beyond beyond that or should do no one
can be comforted in facing death their own or that of a loved one by a
machine programmed to mouth platitudes May our treatments be as free
from harm as possible above all Do no harm you know the words this
should mean embracing therapies both physical and psychological that
are effective without necess necessitating medical intervention in
every case though not an unthinking abandonment of what medical
science has bestowed and for which I'm personally and professionally
very grateful it may also mean consigning some treatments to history
it means paying attention to at its simplest making eye contact with
the living being in front of you not the screen of a computer proper
attention is healing in itself it shows respect induces trust and
gives birth to a relationship will which will sustain our patients and
I might say ourselves what whatever we can or cannot do for them never
see death as a personal failure and know when to desist from what are
called heroic Measures the true hero is the one that respects limits
in the name of compassion and remember to be kind to colleagues and
not forget a sense of humor these are no small human achievements when
under stress which is inevitably where one often finds oneself
kindness and humor are friends of Common Sense and while they cannot
be offered by machines I fear they're being driven out of our world by
too many Grim straight-faced life denying mechanical rules protocols
algorithms and procedures no machines can never be like people but I
worry that people might be becoming more like machines with every
passing day we need courage we need imagination and we need Resolute
adherence to the values that matter most in the words of that great
psychiatrist neurologist and Holocaust Survivor Victor Frankle let us
say yes to life in spite of everything thank you thank you very much
good so we're going to in a minute have some time just for some
general questions given that a lot of this is connected to
neuroscience and a lot of you don't have a neuroscience background we
thought we'd open if you invite the two of you to have a conversation
together so this is Dr Lynn white who is a neuroscientist uh he
directs the brain and Behavior Uh course for our medical students and
he does a lot of very interesting work where in his teaching of
Neuroscience he brings up Concepts and that are best understood from
the perspective of the humanities and I thought we' just have a little
bit of time to let the two of them dialogue together and then I'm
going to invite questions from the audience after that thank you so
much Dr Baker uh thank you Dr molist it's an honor and a privilege to
share the stage with you even for just a few moments and uh for the
benefit of the audience as a neuroscientist I I would like to exercise
some privilege and focus my questions primarily on the foundations of
the ideas that you mentioned in the first 10 or 15 minutes of your
lecture today those ideas that uh comprise the first part of uh Dr
Miguel Christ seminal work which I trust is familiar to many of you in
the audience uh uh the master in his Emissary so I'd like to begin by
turning our attention to one of the very first points you made which
is that the human brain has evolved to sustain necessary and seemingly
paradoxical contingencies on the one hand cooperation but on the other
competition exactly so please help us understand how is this possible
how can cooperation and competition simultaneously characterize the
relationship between the cerebral hemispheres well first I'd say that
they're a principle in nature alog together so that the story of
evolution is usually presented in a very one-sided and very left
hemispheric way the left hemisphere is very keen on competition but
the right hemisphere is more interested in cooperation and indeed
species that survive are not those who have ruthlessly won their way
to the top but those who learned how to collaborate with other species
this is a very wellestablished finding in evolution and so we would
wouldn't expect the human brain or any part of the human being to
abure either one of these we need competition of course it's very
healthful as long as it doesn't become terminal and we need
cooperation and the way in which the hemispheres relate is complicated
but there is this difficulty that the left hemisphere is definitely
about getting something ahead of somebody else grabbing that seed if
you're a bird precisely so that you get it before one of your con
specifics but the right hemispher is looking out for the whole picture
for for predators that may be eyeing you up as you're eyeing your
lunch and for your kin for your mate for your Offspring so these
collaborative and Cooperative ways of of being are there but the the
story of the master in his Emery which is after all in a metapher
suggests that the master the right hemisphere appointed an emissary
because it knew it needed the Emissary it didn't want to compete with
the Emissary it wanted the Emissary to do healthful work that would
benefit the both of them but the Emissary knowing very little compared
with the master and that is not just a a kind of image it's true that
and I unpack this for 400 pages in the beginning of the matter with
things the right hemisphere knows a great deal less understands a
great deal less and is much less reliable on reality than the right
hemisphere but knowing so little it thinks it knows everything and
this was the famous Dunning Krueger effect that the more you know the
more you realize how little you know and the less you know the more
you think you know it all and so I can think of some prominent voices
in science who think they know it all I shall make no further comment
in the way they sorry just to finish in the way they relate it is true
that the right hemisphere communicates more promptly and more with the
left hemisphere than the left hemisphere is willing to communicate in
the opposite direction because it's more internally directed so the
actual structure the neuronal structure and architecture of the right
hemisphere is more diffus with more connections but around the
hemisphere than the left hemisphere which tends to concentrically
focus attention within certain areas so once again this detailed
narrow Focus thing just causes more narrow Focus whereas the right hem
is always going but what is it I don't know and therefore it is not to
return to the whole to have nothing to do with what the left
hemisphere sees to return to the whole is to see that both of them are
needed in the way the right hemisphere understandable just wanted to
say thank you and for the benefit of the audience if if any of you are
curious to uh unpack some of the biology of how the two hemispheres
relate I'm sure either one of us would be happy to to speak with you
uh following the reception or during the reception uh but I did want
to follow up on your response to this question because it leads quite
naturally into an important progression of being that you articulate
which is a progression of right left and then right yes and that
progression provides a coherent way of understanding oneself the world
and one's place in it and I'm wondering if you could say more about
your experience perhaps clinically or otherwise about the consequences
for the integration of Self in the world when one or more stages of
that progression right left right is compromised or underperforms well
much the most common failure of that sequence is the failure of the
left hemisphere to report back to the right spere if you like and it's
very helpful to be able to analyze things uh I'm always told I have an
analytic mind and I did a lot of legal work and so on and I don't you
know I don't have anything against my left hemisphere it's my second
favorite hemisphere I I wouldn't be doing very well in this
conversation if I didn't have an articulate left hemisphere but it's
just when it thinks it's the boss and the I like to use is that of
learning a piece of music so initially you're attracted to it as a
whole that's the right hemisphere which is much more musically
orientated but then you start to practice it you realize you have to
break it up into parts so passages that have to be repeated
mechanically until you master them and you know when you think about
it about the harmonic structure and you see here we return to the
tonic and all this kind of thing but when you go out on stage to
perform you must forget all of that completely otherwise You' give a
terrible performance this doesn't mean that the time was wasted it it
just means it's had its day and we now need to return to the ho that's
been enriched by what the left hemisphere gives now this is an a
metaphor a parable of what we should have but don't have in our
society so we think we understand things simply by taking them apart
as so instead of understanding a motorbike by getting on it and riding
it you understood it by taking it painstaking apart and leaving the
nuts and bolts and everything on the floor and going well search me
what this thing is it doesn't seem to have any meaning or purpose and
that's how we view things now we don't see the whole so that's what
I'd say about that and in medical terms or psychiatric terms what
happens is that people with right hemisphere deficits first of all are
more power seeking and controlling than people with left hemisphere
deficits and they want to they anxious if they're not in control so
the left hemisphere gets paranoid if it doesn't have a grasp of what
it is it might bite me I don't know what to do so it has to be in
control all the time whereas the right hemisphere understands that you
don't need to be in control of everything all the time and in fact for
life to progress at all you have to accept degrees of uncertainty the
other thing that happens and this is evident in both schizophrenia and
in some kinds of autism is that people see things mechanically they
see things not with emotional and social intelligence but as if they
were mechanisms that were being inspected as if from another planet
and one had to work out how they did things so there were lots of
examples that I quote in a chapter on what schizophrenia and autism
can tell us uh where people say exactly this that they see they sort
of they try to work out why did that person say that thing what do
they mean by it because they have to revert to sort of rule-based
learning because they have no intuitive embodied understanding of how
human beings work U and so you you need this awareness and in the most
alive kinds of culture a lot of what is said is not made explicit and
it may be part of the fact that America is a a Melting Pot that when I
went to work at Hopkins and I'm sorry this is probably will sound
disrespectful slightly but I don't mean to be but it was a genu
genuine cultural difference that I learned after a few weeks of saying
things and people were looking at me in a puzzled way and going really
and I say no not really but never mind but I I hadn't realized how
much of the way in which I normally talk is indirectly ironically and
not just stating it as it is and I think the whole of society is
drifting more towards everything has to be made explicit and nothing
that we value is explicit love sex neither of them are good when
they're explicit frankly religion Music Theater narrative poetry art
ritual all these things have to remain at an intuitive non- implicit
level to have their power it's like explaining a joke once you've made
it explicit it just isn't funny well in reading your work there were
so many instances where you had written a sentence that just stopped
me dead in my tracks and I just had to uh put the book down and and
reflect and contemplate on the meaning of what you've just written one
such sentence I'd like to invite you to tell us more about is the
following one could call the mind the brain's experience ience of
itself yes did you want to go on well I I find that both BR
brilliantly concise but also tantalizing and I'd love to hear you say
more about uh what you mean by that people sometimes ask me is there
anything I wrote that I'd want to change that is the one sentence I
would want to to be fair I wrot it a very long time ago now now 18
years ago all on and I hadn't thought as much as I have in the
intervening time about what one can really that that is a a worthless
tautology which suggests that the brain can be able to think about
itself and so forth but we although my my view of the relationship
between matter and Consciousness is not a simple reductive one I
wouldn't want to state that the brain experiences itself our mind
experiences what the brain enables us to experience but I suppose at
that time I was anxious to make bridges with reductionists because I
thought I'd frighten the horses if I said too many things that didn't
sound Orthodox and reductionist so I want to say but it's just the
brain's experience of itself but this was a a moment of feebleness and
and and uh letting myself down so uh there we go well I can assure you
the were duly frightened I I'd like to perhaps just ask two more
questions or one more question okay so um I'll I'll I'll turn to a
thought from someone that I I think we both know and admire uh vs
randin and he has said so insightfully that one of the basic facts of
our being that we so readily take for granted is the embodiment of our
Consciousness and I'm delighted to hear you describe describe
embodiment in such Rich terms today uh similarly you you credit Merlo
Ponte for emphasizing the importance of embodiment ining the basis of
the inter subjective world so please say more about the importance of
embodiment for Consciousness and Inter subjectivity well it's been
said with amusing fake precis Precision that we're only aware of 56%
of all the activity of the nervous system and however you look at that
it's true that we're not aware in the sense of being focused on things
that are that our bodies know that that our brains know that our
nervous system knows and when I was in medical school you know we
recognized that there were nerves to the heart and there were these
efferent nerves that go from the brain to the heart telling it what to
do but unfortunately there were a lot of afferent nerves going back
from the heart reporting to the brain this was a bit of an
embarrassment what are they for they can't be for telling the brain
something so instead they were just reporting pain but that's not I'm
afraid the full story at all and then of course there is the fact that
the gut our human gut contains more neurons than the brain of a dog
and a dog is by no means a stupid animal and I can promise you that
it's they're not all there just to help you go to the restroom so the
the gut is communicating the heart is communicating our muscles are
communicating every part of us is communicating and this is this idea
that is now becoming much more widespread in in biology not
necessarily of the human but just biology of organisms that distant
parts of an organism seem to be aware of the whole situation now this
is very interesting to me and so there's that that embodied knowledge
is both much more than we can articulate and much trer than anything
we can put into words because all the really important stuff is not
susceptible to language language is made for practical purposes to
enable us to establish a certain relationship with people that's legal
or firm and to be able to say where is the hammer and when's my dinner
coming and all this kind of but but it's not terribly good at doing
the subtle stuff and on the whole when reduced to doing conducting a
relationship with a loved one or trying to do therapy over the
telephone although the words are there there's so much missing that
one feels an intimate feeling of loss that something important is not
there so there's that and then there's briefly the idea of inter
subjectivity which I think is a very rich and important idea I try to
distance myself equally from an idea of naive realism that there's
just just stuff out there and our Consciousness looking at it has no
effect on it and also does not alter what it is that we see some of us
goes into whatever it is we see that doesn't invalidate it that makes
it something real actually um but I also don't believe in the sort of
postmodern nonsense that we just make it all up and therefore any idea
is as good as any other I mean for one thing nobody acts on that
everybody acts with purposes and values and they think some things are
trer than others but it would stop philosophy and it would stop
science so instead I think there is a relationship there is always a
relationship sorry to harp on this but it is if you one thing you
should take away is the idea that before there was anything there was
relationship so that relation because I think that is God I think that
is Divinity and in most religions God is seen as a force of love and
if love isn't a relationship I don't know what is so God is relation
no the Trinity shows that God is related to another world and there's
so I could love to give whole days talk on theology here but let me
just come back to this point about inter subjectivity that the base of
our understanding has to be an inter subjective one in which we both
as word was said half create and half perceive the world that we
inhabit and that's not something to shy away from that is a gift and
that's something to celebrate well thank you so much Dr Miguel Chris
we'll reserve the rest of our time for questions from the audience
thank you Dr Baker thank you very much thank yes thank you so I would
like to have some space for questions from the audience at this point
uh we have two microphones in the back they're actually not
disembodied microphones they're with Nikki and Marjorie who are really
the people who made this event successful so I just want to
acknowledge them too yes um microphone coming over there that yeah I
don't know if this uh possible to answer but give it a shot as we I'm
a practicing physician at the end of his practice and as I don't know
if it's just despair but it seems that medicine has become
increasingly the left brain world not just from computers but risk
management and the question is how do we or as the the right brain
Journeys into it to be to connect with the patient it I feel a great
sense of Despair at how to maintain what you call truth beauty
goodness the platonic ideals are the sacred as one is consumed with
the world that I enter to practice medicine and this seems to me to be
profoundly getting worse and rapidly getting worse not better and does
not argur well for uh the patient doctor relationship well if you're
asking me what do we do I'm not sure I've got a simple quick answer I
tend to think that it's important to reconsider the education of
Physicians which is one of the things I mentioned I also think it's
important Physicians to think very hard about their use of machines I
don't say don't ever use them machines are great tools but they are
tools and even the ones that pretend to be much more than tools are
parasites that are pretending to us that they're something like us
they are not and the worry is that we defer to machines in taking
decisions about human lives and what should what should be best for
this patient and I think that's the point at which we've gone much too
far so as Aid Memoir as ways of calculating things the the machine is
very helpful uh processing data much faster than we can do but not
making judgments about human lives I don't mean about life and death
things but anything to do with human lives because they don't know the
whole story by a million miles and we can pretend that they do by
putting in language with which they then are told to go and consult
and try and speak you know in the 18th century they had speaking heads
they weren't as good as whatever it is that Microsoft produces now but
really they're not any different they're just much more clever at
mimicking humans they're still just mimicking humans and and machines
must not be our masters they must be our servants thank thank you and
thank you for coming and it's marvelous to hear you we we seem to be
trapped in a world of language which is all leping and it would seem
that particularly of those of us who are in the caring professions
whether it's medicine or Psychiatry Ministry or whatever ever it may
be that we need to talk more about the language that we use with the
people that we care for what do you have to say to us that helps us
kind of reframe language in a way that um yes can take us into a new
place in our society well effectively there are people who should
never have become clinicians and it's very difficult to to teach them
but the ones who should have become clinicians know instinctively how
to use language and trying to give them courses in how to use words
will make them appear you know mechanical and unspontaneous and will
make them think too much about what words they're using and once you
start doing that you don't come across as somebody who's genuinely
meaning the words you mean you come across as the result of a very
good social skills training course but that's not what we want we want
somebody that we we have that feeling that this is a fellow human
being who understands me it's not rocket science really but there are
certain things that you can't put into somebody if they haven't got it
this was a point made by Madame de in the in the 18th century actually
the late 17th century that if you don't have this understanding in you
I can't give it to you so I think that it's a bit of a waste of time
spending lessons training phys Physicians how to sound more hum get
rid of them they can't sound human they're not human you see that's
why it's very good to have later entrance to Medicine who actually
really want to do the job not just that they see it as a way of
earning a lot of money and they got very good science qualifications
at school I want to respond to the and the other physician in the
state of despair and I think time I think the first thing that I saw
Fall by the way was clinicians deciding how much time they needed to
spend with an individual in order to communicate with them and it's
intuitive it's natural and and the language problems are not so bad I
even those people who struggle with language if they have enough time
to communicate with other people so I'm just going back I'm retired
now I'm going back 45 years and that's the first thing that was the
first blow to our integrity that was the first moral injury was when
they decided that we didn't know how much time we needed to spend with
each patient and so I and I I love what you say about the community
nature and sacred because I think we Physicians have to join up uh
around not how much we're being paid not on the coding system not any
that I think we just have to get together and form a community that
can Define what the essentials of care are yeah thank you I love your
thank you I don't really know what to say except I I was a bit
shattered actually when I heard that there were Physicians who sort of
gain the system in order to make more money because they claimed a
consultation that was longer or whatever and I'm not sure if you
really think like that how you could really enjoy your job or respect
yourself much of the the joy of being a physician is knowing that you
are really engaging with another human being and the the thing that
comes from that is irreplaceable Irreplaceable and I understand that
people work under constraints of time and because uh Private health
care in Britain is extremely small part it's like 2 or 3% when I
decided that I needed to be in private medicine in order to give my
patients the time I thought they deserved and make the decisions for
them that I thought they should have I I was able to do that and
nobody told me I had only so much time it was up to me and I charged
whatever I thought was appropriate to the length of the time I'd spent
so I don't know what the answer to it is but time is a time is one of
those things that we now are all short of and I'd just like to say
this you know we don't we won't be good at anything we won't be good
at being parents or part we won't be good at being teachers or
anything if we are always kind of in a hurry because the good stuff
comes without being hurried it can only happen like that and good
writing has to be like that as I have you know learned to my cost uh
if it's been good I hope it has but yes I mean this this is the
problem about time and one of the ways in which I think we're being
made time poor is by machines intruding into our lives so you know 15
years ago I could solve most Problems by making a 5-minute telephone
call to somebody but now I can easily spend a whole morning frustrated
working through a system that does seems totally illogical doesn't
answer my question has eerik self-referring Loops in it and and and
you know I think did this never get tested on a real human being
surely a few minutes would have shown that this is never going to work
and then you have to hang on in order to speak to somebody on the
other side of the world who doesn't understand anything about the
circumcises where you are an hour and 40 minutes and finally you get
through somebody who can't solve the problem because they've got an
algorithm in front of them and what you're saying to them doesn't
compute this is the world we have created for ourselves my friends
it's not working it's not I mean wake up to it we need to get people
back into our lives also people need to work what are we going to do
just have people sitting around and being paid from the state and
having no satisfaction in their lives if machines take over there are
so much that's going to be wrong and they're not wise they're very
good computation machines but people who are good computation machines
alone are not wise a machine that's a computation machine is never
going to be wise but if you have a powerful tool you need to be wise
enough to know how to use that tool otherwise it's like putting
machine guns in the hands of toddlers we're getting juice this good so
I get to play the Corpus colossum and I'm going to we're going to just
a minute uh divide every let everybody go out for a reception but I
want to invite one question from the right hemisphere I think in the
back uh the posterior lob yes this is working then well uh I just want
to say Dr Migel Christ I came across a video that you gave on Ralston
colleges YouTube channel about a year ago okay and I'm very very
grateful because about 20 years ago I came across another psychologist
who was talking about the importance of white hemispheric dominance
and I'm very grateful because being on the autism spectrum myself I've
learned that by voluntarily choosing to be right hemispheric dominant
I have saved myself from Insanity and complete psychological meltdown
cuz I was someone who could be on the computer 16 hours a day and have
no desire for human connection until I was 13 I didn't have a desire
for human attachments and I've learned through Blood Sweat and Tears
that we need people and that when I have the ability to connect to
people the desire of increases when I have the desire to connect to
people and I act on that desire the ability increases and on top of
this I discovered that if you focus on the right hemisphere the left
hemisphere with all of its abilities becomes more and more powerful if
we focus on the sun we get a stronger Shadow but if if we focus on the
shadow we get nothing so I just want to say thank you very much
because what you are discussing and thankfully at least one other
psychologist as well is the reason I am not dead so thank you very
much and God bless you thank you thank thank you very very much I I'm
I'm moved by that and and thank you so much for saying that and being
open about it and I just want to say that to my surprise I have had
emails from people who said I was always very left hemisphere
dominated or I am on the autistic Spectrum but reading you has helped
me understand things and I now feel I've changed and my relationships
are happier and better so thank you that was very kind of you I want
to thank you for that comment too that was inter I felt drawn drawn to
recognize you well we are going to have a reception outside there'll
be a chance to interact more please go out through the doors and the
sides initially the middle do is going to open in just a second let's
all thank Dr Miguel Chris one last time for his wonderful wonderful
[Applause] address the comments from the audience strike me that
there's a
